### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by KaaeWagner** [bigbluebutton/greenlight#1013]
can not connect to my administrator profil in greenlight

**Comment by farhatahmad** [comment]
Hi @KaaeWagner,

I'm going to need a bit more information than that.

Was there any recent changes? Can you send me the contents of log/production.log when you try to access the profile?

**Comment by KaaeWagner** [comment]
Hope this can help

INFO: [8aa0365d-129f-4606-a9be-9bbf4ae34418] Support: admin@foreningsuddannelser.dk is attempting to login. 
INFO: [8aa0365d-129f-4606-a9be-9bbf4ae34418] Support: admin@foreningsuddannelser.dk has successfully logged in. 
INFO: [8aa0365d-129f-4606-a9be-9bbf4ae34418] method=POST path=/b/u/login format=html controller=SessionsController action=create status=302 duration=353.30 view=0.00 db=5.19 location=https://foreningenonline.dk/b/adm-fwv-xuw host=greenlight 
INFO: [0f59f0af-ccca-41c2-b9aa-b66c793801ff] method=GET path=/b/adm-fwv-xuw format=html controller=RoomsController action=show status=200 duration=113.48 view=28.96 db=5.45 host=greenlight 
INFO: [1d19509e-e169-4295-91f5-edd1ac7d591d] method=GET path=/b/u/gl-kxisambxefpu/edit format=html controller=UsersController action=edit status=500 error='ActionView::Template::Error: undefined method `[]' for nil:NilClass' duration=29.26 view=0.00 db=3.83 host=greenlight 
FATAL: [1d19509e-e169-4295-91f5-edd1ac7d591d]    
FATAL: [1d19509e-e169-4295-91f5-edd1ac7d591d] ActionView::Template::Error (undefined method `[]' for nil:NilClass): 
FATAL: [1d19509e-e169-4295-91f5-edd1ac7d591d]     36:     <%= f.text_field :provider, class: "form-control", readonly: "" %>
[1d19509e-e169-4295-91f5-edd1ac7d591d]     37:     <br>
[1d19509e-e169-4295-91f5-edd1ac7d591d]     38:     <%= f.label t("settings.account.language"), class: "form-label" %>
[1d19509e-e169-4295-91f5-edd1ac7d591d]     39:     <%= f.select :language, language_options, {}, { class: "form-control custom-select" } %>
[1d19509e-e169-4295-91f5-edd1ac7d591d]     40: 
[1d19509e-e169-4295-91f5-edd1ac7d591d]     41:     <% current_user_role = current_user.highest_priority_role %>
[1d19509e-e169-4295-91f5-edd1ac7d591d]     42:     <br> 
FATAL: [1d19509e-e169-4295-91f5-edd1ac7d591d]    
FATAL: [1d19509e-e169-4295-91f5-edd1ac7d591d] app/helpers/users_helper.rb:50:in `block in language_options'
[1d19509e-e169-4295-91f5-edd1ac7d591d] app/helpers/users_helper.rb:48:in `each'
[1d19509e-e169-4295-91f5-edd1ac7d591d] app/helpers/users_helper.rb:48:in `language_options'
[1d19509e-e169-4295-91f5-edd1ac7d591d] app/views/users/components/_account.html.erb:39:in `block in _app_views_users_components__account_html_erb___3968751529995013954_47151565556460'
[1d19509e-e169-4295-91f5-edd1ac7d591d] app/views/users/components/_account.html.erb:16:in `_app_views_users_components__account_html_erb___3968751529995013954_47151565556460'
[1d19509e-e169-4295-91f5-edd1ac7d591d] app/views/users/components/_setting_view.html.erb:24:in `block in _app_views_users_components__setting_view_html_erb___3525060382638967138_47151565672860'
[1d19509e-e169-4295-91f5-edd1ac7d591d] app/views/users/components/_setting_view.html.erb:16:in `_app_views_users_components__setting_view_html_erb___3525060382638967138_47151565672860'
[1d19509e-e169-4295-91f5-edd1ac7d591d] app/views/users/edit.html.erb:32:in `_app_views_users_edit_html_erb___4278402150964409421_47151574161260' 
INFO: [1d19509e-e169-4295-91f5-edd1ac7d591d] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=41.38 view=32.48 db=0.12 host=greenlight 
INFO: [6fd84b91-21d0-41f0-ab98-242773828858] method=GET path=/b/adm-fwv-xuw format=html controller=RoomsController action=show status=200 duration=135.63 view=45.72 db=5.52 host=greenlight

**Comment by farhatahmad** [comment]
This appears to be an issue with the browser language that was fixed in the previous version of Greenlight.

Is it an option for you to update? If not, can you change the browser language to English and try again? (If that works, what language is your browser set to?)

**Comment by KaaeWagner** [comment]
My browser is set to danish. And when i'm setting it to english also US it give me the same error 500. I can open the organization and all the other tabs, but when I try to open the profile tab, it give me the error.

**Comment by KaaeWagner** [comment]
Sorry, but do you mean update BBB?

**Comment by farhatahmad** [comment]
No update Greenlight. You can find the steps here http://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight
