### ISSUE TITLE
Using LDAP - cannot change user's role - Error 500

### ISSUE THREAD

**Issue by philjak** [bigbluebutton/greenlight#1052]
Hey,

I'm using greenlight with LDAP authentification. If I try to change a user's role, I get an error 500. Here is the corresponding log:

```
INFO: [ffc6184c-1b52-4b24-9388-4bad4064262e] method=PATCH path=/b/u/gl-goaynzpadglh/edit format=html controller=UsersController action=update status=500 error='ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...e_id" WHERE "users_roles"."user_id" = $1 ORDER BY "roles"."p...
                                                             ^
: SELECT DISTINCT "roles"."id" FROM "roles" LEFT OUTER JOIN "role_permissions" ON "role_permissions"."role_id" = "roles"."id" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 ORDER BY "roles"."priority" ASC' duration=16.66 view=0.00 db=3.07 host=greenlight 
FATAL: [ffc6184c-1b52-4b24-9388-4bad4064262e]    
FATAL: [ffc6184c-1b52-4b24-9388-4bad4064262e] ActiveRecord::StatementInvalid (PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...e_id" WHERE "users_roles"."user_id" = $1 ORDER BY "roles"."p...
                                                             ^
: SELECT DISTINCT "roles"."id" FROM "roles" LEFT OUTER JOIN "role_permissions" ON "role_permissions"."role_id" = "roles"."id" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 ORDER BY "roles"."priority" ASC): 
FATAL: [ffc6184c-1b52-4b24-9388-4bad4064262e]    
FATAL: [ffc6184c-1b52-4b24-9388-4bad4064262e] app/controllers/concerns/rolify.rb:54:in `update_roles'
[ffc6184c-1b52-4b24-9388-4bad4064262e] app/controllers/users_controller.rb:121:in `update' 
INFO: [ffc6184c-1b52-4b24-9388-4bad4064262e] method=PATCH path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=14.70 view=11.59 db=0.05 host=greenlight 
```

Help would be highly appreciated.

Thanks,
Philip

**Comment by philjak** [comment]
Duplicate #1050

**Comment by farhatahmad** [comment]
Hi @philjak,

The error was fixed in the latest release. Please update and try again
