### ISSUE TITLE
Error 500 when searching Server Recordings

### ISSUE THREAD

**Issue by kurjajuur666** [bigbluebutton/greenlight#1190]
Latest bigbluebutton/greenlight:v2 image.
Is logged as follows:

```
INFO: [aeb070f7-3c25-4f04-8f57-d3630f1d1b5f] method=GET path=/b/admins/recordings
format=html controller=AdminsController action=server_recordings status=500 error='NoMethodError: undefined method 'downcase' for 'nil:NilClass' duration=1968.78 view=0.00 db=3.54 host=greenlight
FATAL: [aeb070f7-3c25-4f04-8f57-d3630f1d1b5f]
FATAL: [aeb070f7-3c25-4f04-8f57-d3630f1d1b5f] NoMethodError (undefined method 'downcase' for nil:NilClass):
FATAL: [aeb070f7-3c25-4f04-8f57-d3630f1d1b5f]
FATAL: [aeb070f7-3c25-4f04-8f57-d3630f1d1b5f] app/controllers/concerns/recorder.rb:91:in 'block in filter_recordings'
[aeb070f7-3c25-4f04-8f57-d3630f1d1b5f] app/controllers/concerns/recorder.rb:82:in 'select'
[aeb070f7-3c25-4f04-8f57-d3630f1d1b5f] app/controllers/concerns/recorder.rb:82:in 'filter_recordings'
[aeb070f7-3c25-4f04-8f57-d3630f1d1b5f] app/controllers/concerns/recorder.rb:71:in 'format_recordings'
[aeb070f7-3c25-4f04-8f57-d3630f1d1b5f] app/controllers/concerns/recorder.rb:47:in 'all_recordings'
[aeb070f7-3c25-4f04-8f57-d3630f1d1b5f] app/controllers/admins_controller.rb:58:in 'server_recordings'
```

**Comment by farhatahmad** [comment]
That seems to happen if user is created without an email (normally through LDAP). I'll tag this as a gub
