### ISSUE TITLE
error 500 when trying to edit user settings

### ISSUE THREAD

**Issue by mm-bln** [bigbluebutton/greenlight#1219]
hello,

first of all thanks for the nice work!

here is my problem: when i try to edit the user settings by clicking edit, 
i get a error 500 in the frontend. in the production.log i find the following:

```
NFO: [2d03f3ac-bdf3-48e3-944f-d40a93520d93] method=GET path=/cnct/admins/edit/gl-ctzthiyrvhsb format=html controller=AdminsController action=edit_user status=500 error='ActionView::Template::Error: undefined method `[]' for nil:NilClass' duration=16.35 view=0.00 db=1.49 host=greenlight 
FATAL: [2d03f3ac-bdf3-48e3-944f-d40a93520d93]    
FATAL: [2d03f3ac-bdf3-48e3-944f-d40a93520d93] ActionView::Template::Error (undefined method `[]' for nil:NilClass): 
FATAL: [2d03f3ac-bdf3-48e3-944f-d40a93520d93]     36:     <%= f.text_field :provider, class: "form-control", readonly: "" %>
[2d03f3ac-bdf3-48e3-944f-d40a93520d93]     37:     <br>
[2d03f3ac-bdf3-48e3-944f-d40a93520d93]     38:     <%= f.label t("settings.account.language"), class: "form-label" %>
[2d03f3ac-bdf3-48e3-944f-d40a93520d93]     39:     <%= f.select :language, language_options, {}, { class: "form-control custom-select" } %>
[2d03f3ac-bdf3-48e3-944f-d40a93520d93]     40: 
[2d03f3ac-bdf3-48e3-944f-d40a93520d93]     41:     <% current_user_role = current_user.highest_priority_role %>
[2d03f3ac-bdf3-48e3-944f-d40a93520d93]     42:     <br> 
FATAL: [2d03f3ac-bdf3-48e3-944f-d40a93520d93]    
FATAL: [2d03f3ac-bdf3-48e3-944f-d40a93520d93] app/helpers/users_helper.rb:50:in `block in language_options'
[2d03f3ac-bdf3-48e3-944f-d40a93520d93] app/helpers/users_helper.rb:48:in `each'
[2d03f3ac-bdf3-48e3-944f-d40a93520d93] app/helpers/users_helper.rb:48:in `language_options'
```

i had already made some adjustments to the translations but i don't think that could be the cause!?
bbb and greenlight have been restarted. problem still exists.
bbb and greenlight were reinstalled via bbb-install script, only two days ago, 
so i wanted to check here before trying an update from greenlight.

any help would be appreciated!

**Comment by farhatahmad** [comment]
Yeah the issue is the change you made to the language file, the syntax of it is incorrect. You can try pasting it here to see what the issue is http://www.yamllint.com/

**Comment by mm-bln** [comment]
i checked the syntax of the changes i've made with yamllint but there wasn't any error.
anyway, i've reinstalled greenlight with the help of the manual for [customizing](https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-greenlight).
now there is no more error and the user settings can be adjusted. 

thank you
