### ISSUE TITLE
Error 500 while accessing to user profile

### ISSUE THREAD

**Issue by efazenda** [bigbluebutton/greenlight#1243]
Dear support, 

I have the following issue, when accessing the Account profile of a user, or by editing uses profile using a Adminnistrator account , get an Error 500.

Error Message : 
![image](https://user-images.githubusercontent.com/2209728/78892176-2dfe0b80-7a69-11ea-89cd-b04213de377a.png)

I have a customize Greenlight setup with my docker image that i rebuild every time i made a modification.

I have modified the en.yml and fr.yml file to have custom Welcome page etc and moved other YAML of languages that i don't want to use in another directory 

`~/greenlight# ls -lR config/locales/
config/locales/:
total 28
drwxr-xr-x 2 root root  4096 Apr  8 14:31 backup
-rwxr-xr-x 1 root root 24354 Apr  9 12:39 en.yml

config/locales/backup:
total 804
-rw-r--r-- 1 root root 33840 Apr  8 13:46 ar.yml
-rw-r--r-- 1 root root 37647 Apr  8 13:48 bg.yml
-rw-r--r-- 1 root root 26834 Apr  8 13:46 cs.yml
-rw-r--r-- 1 root root 28572 Apr  8 13:46 de_DE.yml
-rw-r--r-- 1 root root 14417 Apr  8 13:46 el.yml
-rwxr-xr-x 1 root root 24354 Apr  8 13:59 en.yml
-rw-r--r-- 1 root root 27534 Apr  8 13:46 es_MX.yml
-rw-r--r-- 1 root root 24705 Apr  8 13:46 es.yml
-rw-r--r-- 1 root root 36519 Apr  8 13:46 fa_IR.yml
-rw-r--r-- 1 root root 15924 Apr  8 14:01 fr.yml
-rw-r--r-- 1 root root 20905 Apr  8 13:46 hi_IN.yml
-rw-r--r-- 1 root root 27778 Apr  8 13:46 hu_HU.yml
-rw-r--r-- 1 root root 19333 Apr  8 13:46 it.yml
-rw-r--r-- 1 root root 30710 Apr  8 13:46 ja_JP.yml
-rw-r--r-- 1 root root 27905 Apr  8 13:46 lv.yml
-rw-r--r-- 1 root root 22477 Apr  8 13:46 nb.yml
-rw-r--r-- 1 root root 26902 Apr  8 13:48 nl.yml
-rw-r--r-- 1 root root 23597 Apr  8 13:46 pl_PL.yml
-rw-r--r-- 1 root root 23565 Apr  8 13:46 pt_BR.yml
-rw-r--r-- 1 root root 13824 Apr  8 13:46 pt.yml
-rw-r--r-- 1 root root 39126 Apr  8 13:46 ru.yml
-rw-r--r-- 1 root root 24154 Apr  8 13:46 sk_SK.yml
-rw-r--r-- 1 root root 22583 Apr  8 13:46 sv_SE.yml
-rw-r--r-- 1 root root 45595 Apr  8 13:46 th.yml
-rw-r--r-- 1 root root 26632 Apr  8 13:48 tr_TR.yml
-rw-r--r-- 1 root root 27415 Apr  8 13:46 tr.yml
-rw-r--r-- 1 root root 39043 Apr  8 13:46 uk.yml
-rw-r--r-- 1 root root 17562 Apr  8 13:46 vi_VN.yml
-rw-r--r-- 1 root root 22819 Apr  8 13:46 zh_CN.yml`

On the logs of Greenlight I have the following errors : 

`INFO: [128383da-d482-4b8b-a029-5133d7a93962] method=GET path=/b/u/gl-xcnlccdeykkt/edit format=html controller=UsersController action=edit status=500 error='ActionView::Template::Error: undefined method `[]' for nil:NilClass' duration=28.93 view=0.00 db=6.92 host=greenlight
FATAL: [128383da-d482-4b8b-a029-5133d7a93962]
FATAL: [128383da-d482-4b8b-a029-5133d7a93962] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
FATAL: [128383da-d482-4b8b-a029-5133d7a93962]     36:     <%= f.text_field :provider, class: "form-control", readonly: "" %>
[128383da-d482-4b8b-a029-5133d7a93962]     37:     <br>
[128383da-d482-4b8b-a029-5133d7a93962]     38:     <%= f.label t("settings.account.language"), class: "form-label" %>
[128383da-d482-4b8b-a029-5133d7a93962]     39:     <%= f.select :language, language_options, {}, { class: "form-control custom-select" } %>
[128383da-d482-4b8b-a029-5133d7a93962]     40:
[128383da-d482-4b8b-a029-5133d7a93962]     41:     <% current_user_role = current_user.highest_priority_role %>
[128383da-d482-4b8b-a029-5133d7a93962]     42:     <br>
FATAL: [128383da-d482-4b8b-a029-5133d7a93962]
FATAL: [128383da-d482-4b8b-a029-5133d7a93962] app/helpers/users_helper.rb:50:in `block in language_options'
[128383da-d482-4b8b-a029-5133d7a93962] app/helpers/users_helper.rb:48:in `each'
[128383da-d482-4b8b-a029-5133d7a93962] app/helpers/users_helper.rb:48:in `language_options'
[128383da-d482-4b8b-a029-5133d7a93962] app/views/users/components/_account.html.erb:39:in `block in _app_views_users_components__account_html_erb___710352997926656109_47448151746580'
[128383da-d482-4b8b-a029-5133d7a93962] app/views/users/components/_account.html.erb:16:in `_app_views_users_components__account_html_erb___710352997926656109_47448151746580'
[128383da-d482-4b8b-a029-5133d7a93962] app/views/users/components/_setting_view.html.erb:24:in `block in _app_views_users_components__setting_view_html_erb___2985916278697341254_47448151799740'
[128383da-d482-4b8b-a029-5133d7a93962] app/views/users/components/_setting_view.html.erb:16:in `_app_views_users_components__setting_view_html_erb___2985916278697341254_47448151799740'
[128383da-d482-4b8b-a029-5133d7a93962] app/views/users/edit.html.erb:32:in `_app_views_users_edit_html_erb___441279928218861497_47448152279940'
INFO: [128383da-d482-4b8b-a029-5133d7a93962] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=19.48 view=15.07 db=0.07 host=greenlight`

My running setup is the following : 

Ubuntu 16.04 LTS up to date
Greenlight latest release upstream/v2

Do you have an ideao on what is wrong here ?

If you need more information d'ont hesitate.

Best Regards, Edouard Fazenda

**Comment by farhatahmad** [comment]
Yeah that's the error that appears when you mess with the language files. The Rails language gem is extremely picky with its structure. Try moving the `backup` folder outside the `locales` folder

**Comment by efazenda** [comment]
Hi

Thanks it's that, all is ok now ! 

Have a nice day ! 

By and thanks again.
