### ISSUE TITLE
Error 500 when click edit user or profile section

### ISSUE THREAD

**Issue by vurulkan** [bigbluebutton/greenlight#1405]
Hello,

I give 500 error when i click edit user or profile section (both the same link?). Here is a my log;

`INFO: [c12d4151-7e4d-462d-9de7-042caeac2404] Support: Auth user test@xxx.com is attempting to login. 
INFO: [c12d4151-7e4d-462d-9de7-042caeac2404] Support: test@xxx.com has successfully logged in. 
INFO: [c12d4151-7e4d-462d-9de7-042caeac2404] method=POST path=/b/auth/ldap format=html controller=SessionsController action=ldap status=302 duration=36.05 view=0.00 db=4.78 location=https://talk.xxx.com/b/tes-tda-ker host=greenlight 
INFO: [23af290a-3907-4b7d-b51d-032f9bf12768] method=GET path=/b/tes-tda-ker format=html controller=RoomsController action=show status=200 duration=80.69 view=25.27 db=7.83 host=greenlight 
INFO: [957853db-db43-45a7-a5ed-11a27bfb8dba] method=GET path=/b/u/gl-tedhbezxmffg/edit format=html controller=UsersController action=edit status=500 error='ActionView::Template::Error: undefined method `[]' for nil:NilClass' duration=29.94 view=0.00 db=1.96 host=greenlight 
FATAL: [957853db-db43-45a7-a5ed-11a27bfb8dba]    
FATAL: [957853db-db43-45a7-a5ed-11a27bfb8dba] ActionView::Template::Error (undefined method `[]' for nil:NilClass): 
FATAL: [957853db-db43-45a7-a5ed-11a27bfb8dba]     36:     <%= f.text_field :provider, class: "form-control", readonly: "" %>
[957853db-db43-45a7-a5ed-11a27bfb8dba]     37:     <br>
[957853db-db43-45a7-a5ed-11a27bfb8dba]     38:     <%= f.label t("settings.account.language"), class: "form-label" %>
[957853db-db43-45a7-a5ed-11a27bfb8dba]     39:     <%= f.select :language, language_options, {}, { class: "form-control custom-select" } %>
[957853db-db43-45a7-a5ed-11a27bfb8dba]     40: 
[957853db-db43-45a7-a5ed-11a27bfb8dba]     41:     <% current_user_role = current_user.highest_priority_role %>
[957853db-db43-45a7-a5ed-11a27bfb8dba]     42:     <br> 
FATAL: [957853db-db43-45a7-a5ed-11a27bfb8dba]    
FATAL: [957853db-db43-45a7-a5ed-11a27bfb8dba] app/helpers/users_helper.rb:50:in `block in language_options'
[957853db-db43-45a7-a5ed-11a27bfb8dba] app/helpers/users_helper.rb:48:in `each'
[957853db-db43-45a7-a5ed-11a27bfb8dba] app/helpers/users_helper.rb:48:in `language_options'
[957853db-db43-45a7-a5ed-11a27bfb8dba] app/views/users/components/_account.html.erb:39:in `block in _app_views_users_components__account_html_erb___381643985789713110_47162840698700'
[957853db-db43-45a7-a5ed-11a27bfb8dba] app/views/users/components/_account.html.erb:16:in `_app_views_users_components__account_html_erb___381643985789713110_47162840698700'
[957853db-db43-45a7-a5ed-11a27bfb8dba] app/views/users/components/_setting_view.html.erb:24:in `block in _app_views_users_components__setting_view_html_erb__4031635821702705259_47162840716140'
[957853db-db43-45a7-a5ed-11a27bfb8dba] app/views/users/components/_setting_view.html.erb:16:in `_app_views_users_components__setting_view_html_erb__4031635821702705259_47162840716140'
[957853db-db43-45a7-a5ed-11a27bfb8dba] app/views/users/edit.html.erb:32:in `_app_views_users_edit_html_erb___2991014839308949719_47162840804140' 
INFO: [957853db-db43-45a7-a5ed-11a27bfb8dba] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=24.84 view=19.62 db=0.08 host=greenlight `

**Comment by vurulkan** [comment]
Deleted hy.yml and solved the problem. #1337
