### ISSUE TITLE
Greenlight: getting 404 Not found

### ISSUE THREAD

**Issue by Ninad-iitbombay** [bigbluebutton/greenlight#1504]
Hi,
I have installed bbb+greenlight using tutorial available on bbb website.
BBB is working fine. 
But greenlight container keeps restarting. I kindly request you to guide me in this regards.

`sudo docker ps -a `
`
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                          PORTS                      NAMES
bdf6700d0ba8        bigbluebutton/greenlight:v2   "bin/start"              3 minutes ago       Restarting (1) 20 seconds ago                              greenlight-v2
ec02ed81625e        postgres:9.5                  "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes                    127.0.0.1:5432->5432/tcp   greenlight_db_1
`
**The output of docker logs**

`2020-05-04T16:58:39.348173537Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
2020-05-04T16:58:39.348176867Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
2020-05-04T16:58:39.348180350Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
2020-05-04T16:58:39.348183611Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/base.rb:27:in `<top (required)>'
2020-05-04T16:58:39.348186825Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
2020-05-04T16:58:39.348189841Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
2020-05-04T16:58:39.348192898Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
2020-05-04T16:58:39.348195876Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
2020-05-04T16:58:39.348199217Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2020-05-04T16:58:39.348202223Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
2020-05-04T16:58:39.348205198Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
2020-05-04T16:58:39.348208141Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
2020-05-04T16:58:39.348211028Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
2020-05-04T16:58:39.348214138Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
2020-05-04T16:58:39.348217224Z /usr/local/bin/bundle:23:in `load'
2020-05-04T16:58:39.348220047Z /usr/local/bin/bundle:23:in `<main>'
2020-05-04T16:58:39.348223954Z
2020-05-04T16:58:39.348226454Z Caused by:
2020-05-04T16:58:39.348228903Z LoadError: cannot load such file -- active_record/connection_adapters/_adapter
2020-05-04T16:58:39.348243443Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require'
2020-05-04T16:58:39.348247768Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
2020-05-04T16:58:39.348250958Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
2020-05-04T16:58:39.348253980Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
2020-05-04T16:58:39.348260715Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/connection_specification.rb:191:in `spec'
2020-05-04T16:58:39.348263979Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:956:in `establish_connection'
2020-05-04T16:58:39.348267015Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:60:in `establish_connection'
2020-05-04T16:58:39.348270050Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
2020-05-04T16:58:39.348273228Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
2020-05-04T16:58:39.348276212Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
2020-05-04T16:58:39.348278904Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
2020-05-04T16:58:39.348281814Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
2020-05-04T16:58:39.348284648Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
2020-05-04T16:58:39.348287309Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
2020-05-04T16:58:39.348289918Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
2020-05-04T16:58:39.348293066Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
2020-05-04T16:58:39.348295886Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/base.rb:27:in `<top (required)>'
2020-05-04T16:58:39.348298596Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
2020-05-04T16:58:39.348301219Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
2020-05-04T16:58:39.348304315Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
2020-05-04T16:58:39.348306924Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
2020-05-04T16:58:39.348309605Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2020-05-04T16:58:39.348312347Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
2020-05-04T16:58:39.348315241Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
2020-05-04T16:58:39.348318040Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
2020-05-04T16:58:39.348323930Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
2020-05-04T16:58:39.348327371Z /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
2020-05-04T16:58:39.348330430Z /usr/local/bin/bundle:23:in `load'
2020-05-04T16:58:39.348333299Z /usr/local/bin/bundle:23:in `<main>'
2020-05-04T16:58:39.348335853Z Tasks: TOP => db:schema:load => db:load_config
2020-05-04T16:58:39.348338489Z (See full trace by running task with --trace)
2020-05-04T16:58:41.410326257Z yarn install v1.3.2
2020-05-04T16:58:41.436236213Z [1/4] Resolving packages...
2020-05-04T16:58:41.439268966Z success Already up-to-date.
2020-05-04T16:58:41.439704106Z Done in 0.03s.
2020-05-04T16:58:42.240210854Z Puma starting in single mode...
2020-05-04T16:58:42.240229915Z * Version 3.12.4 (ruby 2.5.1-p57), codename: Llamas in Pajamas
2020-05-04T16:58:42.240234398Z * Min threads: 5, max threads: 5
2020-05-04T16:58:42.240237312Z * Environment: production
2020-05-04T16:58:43.655287919Z ! Unable to load application: LoadError: Could not load the '' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile.
2020-05-04T16:58:43.655316609Z bundler: failed to load command: puma (/usr/src/app/vendor/bundle/ruby/2.5.0/bin/puma)
2020-05-04T16:58:43.655387214Z LoadError: Could not load the '' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile.
2020-05-04T16:58:43.655399602Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require'
2020-05-04T16:58:43.655402859Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
2020-05-04T16:58:43.655405297Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
2020-05-04T16:58:43.655407407Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
2020-05-04T16:58:43.655409567Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/connection_specification.rb:191:in `spec'
2020-05-04T16:58:43.655411784Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:956:in `establish_connection'
2020-05-04T16:58:43.655413936Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:60:in `establish_connection'
2020-05-04T16:58:43.655415922Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
2020-05-04T16:58:43.655426676Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
2020-05-04T16:58:43.655428921Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
2020-05-04T16:58:43.655430977Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
2020-05-04T16:58:43.655432965Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
2020-05-04T16:58:43.655435026Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
2020-05-04T16:58:43.655437002Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
2020-05-04T16:58:43.655439497Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
2020-05-04T16:58:43.655441644Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
2020-05-04T16:58:43.655443702Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/base.rb:27:in `<top (required)>'
2020-05-04T16:58:43.655445763Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
2020-05-04T16:58:43.655447829Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
2020-05-04T16:58:43.655449878Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
2020-05-04T16:58:43.655452096Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
2020-05-04T16:58:43.655454161Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2020-05-04T16:58:43.655456135Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
2020-05-04T16:58:43.655458703Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
2020-05-04T16:58:43.655461418Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
2020-05-04T16:58:43.655463826Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activestorage-5.2.3/app/models/active_storage/attachment.rb:9:in `<top (required)>'
2020-05-04T16:58:43.655466563Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
2020-05-04T16:58:43.655469589Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
2020-05-04T16:58:43.655476465Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
2020-05-04T16:58:43.655479886Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
2020-05-04T16:58:43.655482061Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2020-05-04T16:58:43.655484098Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
2020-05-04T16:58:43.655486160Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
2020-05-04T16:58:43.655488250Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
2020-05-04T16:58:43.655490321Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:378:in `block in require_or_load'
2020-05-04T16:58:43.655492373Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
2020-05-04T16:58:43.655494422Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
2020-05-04T16:58:43.655496493Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
2020-05-04T16:58:43.655498559Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
2020-05-04T16:58:43.655501198Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `load_interlock'
2020-05-04T16:58:43.655504509Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:356:in `require_or_load'
2020-05-04T16:58:43.655507062Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `block in require_or_load'
2020-05-04T16:58:43.655509117Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
2020-05-04T16:58:43.655511182Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:47:in `require_or_load'
2020-05-04T16:58:43.655513265Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:334:in `depend_on'
2020-05-04T16:58:43.655515541Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:85:in `depend_on'
2020-05-04T16:58:43.655517650Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:246:in `require_dependency'
2020-05-04T16:58:43.655519703Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
2020-05-04T16:58:43.655521704Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `each'
2020-05-04T16:58:43.655525641Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:477:in `block in eager_load!'
2020-05-04T16:58:43.655528269Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `each'
2020-05-04T16:58:43.655530254Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:475:in `eager_load!'
2020-05-04T16:58:43.655532185Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:356:in `eager_load!'
2020-05-04T16:58:43.655534131Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `each'
2020-05-04T16:58:43.655536102Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
2020-05-04T16:58:43.655538153Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
2020-05-04T16:58:43.655540105Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
2020-05-04T16:58:43.655542027Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
2020-05-04T16:58:43.655543986Z   /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
2020-05-04T16:58:43.655545905Z   /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2020-05-04T16:58:43.655547847Z   /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
2020-05-04T16:58:43.655549785Z   /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
2020-05-04T16:58:43.655551748Z   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
2020-05-04T16:58:43.655553632Z   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
2020-05-04T16:58:43.655555534Z   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
2020-05-04T16:58:43.655557459Z   /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
2020-05-04T16:58:43.655559606Z   /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
2020-05-04T16:58:43.655561589Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
2020-05-04T16:58:43.655563559Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
2020-05-04T16:58:43.655565502Z   /usr/src/app/config/environment.rb:23:in `<top (required)>'
2020-05-04T16:58:43.655567472Z   config.ru:5:in `require_relative'
2020-05-04T16:58:43.655569321Z   config.ru:5:in `block in <main>'
2020-05-04T16:58:43.655571409Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
2020-05-04T16:58:43.655574229Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
2020-05-04T16:58:43.655577758Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
2020-05-04T16:58:43.655583993Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
2020-05-04T16:58:43.655586112Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/configuration.rb:320:in `load_rackup'
2020-05-04T16:58:43.655588101Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/configuration.rb:245:in `app'
2020-05-04T16:58:43.655590060Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/runner.rb:147:in `load_and_bind'
2020-05-04T16:58:43.655592011Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/single.rb:98:in `run'
2020-05-04T16:58:43.655593938Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/launcher.rb:186:in `run'
2020-05-04T16:58:43.655595890Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/cli.rb:80:in `run'
2020-05-04T16:58:43.655613180Z   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/bin/puma:10:in `<top (required)>'
2020-05-04T16:58:43.655616589Z   /usr/src/app/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
2020-05-04T16:58:43.655618692Z   /usr/src/app/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
`

**Comment by farhatahmad** [comment]
Looks like the database might not be starting up correctly. Whats the output of `docker logs greenlight_db_1`

**Comment by Ninad-iitbombay** [comment]
Thank you for the quick response.
**Below is the out of docker logs greenlight_db_1**

`2020-05-04T16:55:01.216343621Z
2020-05-04T16:55:01.216369725Z PostgreSQL Database directory appears to contain a database; Skipping initialization
2020-05-04T16:55:01.216374078Z
2020-05-04T16:55:02.086402145Z LOG:  database system was shut down at 2020-05-04 16:53:31 UTC
2020-05-04T16:55:02.455784716Z LOG:  MultiXact member wraparound protections are now enabled
2020-05-04T16:55:02.540768110Z LOG:  autovacuum launcher started
2020-05-04T16:55:02.540782253Z LOG:  database system is ready to accept connections
`

**Comment by Ninad-iitbombay** [comment]
One thing I forgot to mention is I am running this docker under LXC container
My LXC container config is
4 core, 8Gb mem, 50G disk,
Ubuntu 16.04
running bbb + docker for greenlight

**Comment by Ninad-iitbombay** [comment]
Hi,
Currently, the issue is resolved after commenting below lines in .env file.

`
DB_ADAPTER=
DB_HOST=
DB_NAME=
DB_USERNAME=
DB_PASSWORD=
`

**Comment by sergeyshaklein** [comment]
> Hi,
> Currently, the issue is resolved after commenting below lines in .env file.
> 
> `DB_ADAPTER= DB_HOST= DB_NAME= DB_USERNAME= DB_PASSWORD=`

I have a similar error. What did you comment on to remove the error?
