### ISSUE TITLE
How to improve development environment?

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/greenlight#1531]
We use a customize build of Greenlight. We rely on Postgres DB features and we can not use SQLite in dev environment (beside It is best practice to use the same adapter in both environment). As a result we continue to use docker in dev env. The problem is that the current setup does not support to run Rails in dev env. My biggest problem is that I have to rebuild the image with every code change. Adding a volume in `docker-compose.yml` will not works:

```yml
services:
  app:
...
    volumes:
      - .:/usr/src/app

```
This is from the logs:
```
greenlight-v2 | bundler: failed to load command: rake (/usr/local/bin/rake) Bundler::GemNotFound: Could not find rake-13.0.1 in any of the sources /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:91:in `block in materialize' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `map!' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `materialize' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:171:in `specs' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:238:in `specs_for' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:227:in `requested_specs' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:108:in `block in definition_method' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:20:in `setup' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>' /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require' /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 | >>> Database initialization
greenlight-v2 | bundler: failed to load command: rake (/usr/local/bin/rake)
greenlight-v2 | Bundler::GemNotFound: Could not find rake-13.0.1 in any of the sources
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:91:in `block in materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `map!'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:171:in `specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:238:in `specs_for'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:227:in `requested_specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:108:in `block in definition_method'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:20:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 | bundler: failed to load command: rake (/usr/local/bin/rake)
greenlight-v2 | Bundler::GemNotFound: Could not find rake-13.0.1 in any of the sources
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:91:in `block in materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `map!'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:171:in `specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:238:in `specs_for'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:227:in `requested_specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:108:in `block in definition_method'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:20:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 | bundler: command not found: puma
greenlight-v2 | Install missing gem executables with `bundle install`
```

How can I configure docker to load my changes without rebuild?

Thanks

**Comment by farhatahmad** [comment]
I personally run it as a regular Rails application on my local machine. Maybe others can chime in on how they have their dev environment set up

**Comment by ichdasich** [comment]
I am also using the same deploy for dev and prod; Your approach of trying to make docker reload the app without rebuilding the container kind of goes against the paradigm of docker. If you just want to have to restart the rails app to test changes, i'd guess @farhatahmad 's suggestion is the way to go.

Maybe just plug a CI pipeline, so on push the rebuild is handled automatically and pushing to their production env, taking away that overhead from the devs?

**Comment by farhatahmad** [comment]
Going to close this as it doesn't seem anyone else is going to chime in. @mabras If you plan on doing a lot of dev work, I highly suggest you install Rails and run Greenlight as a rails application. It will save you a lot of work
