### ISSUE TITLE
greenlight is not starting

### ISSUE THREAD

**Issue by chillihilli** [bigbluebutton/greenlight#2010]
Hi there,
on a clean install I cannot start greenlight:
```
~/greenlight# docker-compose up -d
greenlight_db_1 is up-to-date
Starting greenlight-v2 ... error

ERROR: for greenlight-v2  Cannot start service app: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/80d6cf6316837ab9d5edcb3f81464755f8769f1954634eb536ab965b581901fa/log.json: no such file or directory): runc did not terminate sucessfully: unknown

ERROR: for app  Cannot start service app: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/80d6cf6316837ab9d5edcb3f81464755f8769f1954634eb536ab965b581901fa/log.json: no such file or directory): runc did not terminate sucessfully: unknown
ERROR: Encountered errors while bringing up the project.

```

**Output of `docker version`:**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**
```
Client:
 Debug Mode: false
 Plugins:
WARNING: Plugin "/usr/libexec/docker/cli-plugins/docker-app" is not valid: failed to fetch metadata: exit status 2

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.4.0
 Operating System: Ubuntu 16.04.7 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 16GiB
 Name: h2882585.stratoserver.net
 ID: D264:EBUW:JCN7:JJZM:IKAP:HAY3:LHBB:AMTW:VND5:KPNT:YRKW:X7A6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

BBB is running but Greenlight is not. Can anybody help please?

Kind Regards
Michael

**Comment by chillihilli** [comment]
After a reeboot greenlight seemed to work:
```
# docker-compose up -d
greenlight_db_1 is up-to-date
Starting greenlight-v2 ... done
```
but trying to create a user resulting in:
```
# docker exec greenlight-v2 bundle exec rake user:create["name","email","password","user"]
runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f90b638e438 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f90b638e438
stack: frame={sp:0x7ffcc7b76a58, fp:0x0} stack=[0x7ffcc7377fc0,0x7ffcc7b77000)
00007ffcc7b76958:  0000000000000000  2f3a6e69622f6c61 
00007ffcc7b76968:  6e6962732f727375  69622f7273752f3a 
00007ffcc7b76978:  3a6e6962732f3a6e  73752f3a6e69622f 
00007ffcc7b76988:  3a73656d61672f72  636f6c2f7273752f 
00007ffcc7b76998:  73656d61672f6c61  2a3a36333b30303d 
00007ffcc7b769a8:  3b30303d616b6d2e  33706d2e2a3a3633 
00007ffcc7b769b8:  2a3a36333b30303d  3b30303d63706d2e 
00007ffcc7b769c8:  67676f2e2a3a3633  2a3a36333b30303d 
00007ffcc7b769d8:  333b30303d61722e  3d7661772e2a3a36 
00007ffcc7b769e8:  2e2a3a36333b3030  333b30303d61676f 
00007ffcc7b769f8:  7375706f2e2a3a36  2a3a363300000013 
00007ffcc7b76a08:  0000000000000120  00007ffcc7b76a80 
00007ffcc7b76a18:  0000000000000000  3d76617700000001 
00007ffcc7b76a28:  00007f90b671e700  000055ffd0f99b34 
00007ffcc7b76a38:  000055ffd44942f0  0000000000000000 
00007ffcc7b76a48:  000055ffd0f4138c  0000000000000000 
00007ffcc7b76a58: <00007f90b639003a  0000000000000020 
00007ffcc7b76a68:  0000000000000000  0000000000000000 
00007ffcc7b76a78:  0000000000000000  0000000000000000 
00007ffcc7b76a88:  0000000000000000  0000000000000000 
00007ffcc7b76a98:  0000000000000000  0000000000000000 
00007ffcc7b76aa8:  0000000000000000  0000000000000000 
00007ffcc7b76ab8:  0000000000000000  0000000000000000 
00007ffcc7b76ac8:  0000000000000000  0000000000000000 
00007ffcc7b76ad8:  0000000000000000  0000000000000000 
00007ffcc7b76ae8:  00007f90b64503a9  0000000000000000 
00007ffcc7b76af8:  00007f90b63d1c0f  00007f90b671e540 
00007ffcc7b76b08:  0000000000000001  00007f90b671e5c3 
00007ffcc7b76b18:  0000000000000000  000055ffd0f4138c 
00007ffcc7b76b28:  00007f90b63d3419  00007f90b671e540 
00007ffcc7b76b38:  00007f90b671e540  000000000000000a 
00007ffcc7b76b48:  000055ffd44942f0  0000000000000000 
runtime: unknown pc 0x7f90b638e438
stack: frame={sp:0x7ffcc7b76a58, fp:0x0} stack=[0x7ffcc7377fc0,0x7ffcc7b77000)
00007ffcc7b76958:  0000000000000000  2f3a6e69622f6c61 
00007ffcc7b76968:  6e6962732f727375  69622f7273752f3a 
00007ffcc7b76978:  3a6e6962732f3a6e  73752f3a6e69622f 
00007ffcc7b76988:  3a73656d61672f72  636f6c2f7273752f 
00007ffcc7b76998:  73656d61672f6c61  2a3a36333b30303d 
00007ffcc7b769a8:  3b30303d616b6d2e  33706d2e2a3a3633 
00007ffcc7b769b8:  2a3a36333b30303d  3b30303d63706d2e 
00007ffcc7b769c8:  67676f2e2a3a3633  2a3a36333b30303d 
00007ffcc7b769d8:  333b30303d61722e  3d7661772e2a3a36 
00007ffcc7b769e8:  2e2a3a36333b3030  333b30303d61676f 
00007ffcc7b769f8:  7375706f2e2a3a36  2a3a363300000013 
00007ffcc7b76a08:  0000000000000120  00007ffcc7b76a80 
00007ffcc7b76a18:  0000000000000000  3d76617700000001 
00007ffcc7b76a28:  00007f90b671e700  000055ffd0f99b34 
00007ffcc7b76a38:  000055ffd44942f0  0000000000000000 
00007ffcc7b76a48:  000055ffd0f4138c  0000000000000000 
00007ffcc7b76a58: <00007f90b639003a  0000000000000020 
00007ffcc7b76a68:  0000000000000000  0000000000000000 
00007ffcc7b76a78:  0000000000000000  0000000000000000 
00007ffcc7b76a88:  0000000000000000  0000000000000000 
00007ffcc7b76a98:  0000000000000000  0000000000000000 
00007ffcc7b76aa8:  0000000000000000  0000000000000000 
00007ffcc7b76ab8:  0000000000000000  0000000000000000 
00007ffcc7b76ac8:  0000000000000000  0000000000000000 
00007ffcc7b76ad8:  0000000000000000  0000000000000000 
00007ffcc7b76ae8:  00007f90b64503a9  0000000000000000 
00007ffcc7b76af8:  00007f90b63d1c0f  00007f90b671e540 
00007ffcc7b76b08:  0000000000000001  00007f90b671e5c3 
00007ffcc7b76b18:  0000000000000000  000055ffd0f4138c 
00007ffcc7b76b28:  00007f90b63d3419  00007f90b671e540 
00007ffcc7b76b38:  00007f90b671e540  000000000000000a 
00007ffcc7b76b48:  000055ffd44942f0  0000000000000000 

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0x55ffd194a9b8, 0xc000098058, 0x170e, 0x3)
	/usr/local/go/src/runtime/proc.go:304 +0xe6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
runtime.chanrecv(0xc000098000, 0x0, 0xc000000101, 0x55ffcf772cd0)
	/usr/local/go/src/runtime/chan.go:524 +0x2ec
runtime.chanrecv1(0xc000098000, 0x0)
	/usr/local/go/src/runtime/chan.go:406 +0x2b
runtime.gcenable()
	/usr/local/go/src/runtime/mgc.go:212 +0x97
runtime.main()
	/usr/local/go/src/runtime/proc.go:166 +0x129
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1

rax    0x0
rbx    0x7f90b671e700
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x95a
rsi    0x95a
rbp    0x55ffd0f99b34
rsp    0x7ffcc7b76a58
r8     0x7f90b671f770
r9     0x7f90b6d53700
r10    0x8
r11    0x206
r12    0x55ffd44942f0
r13    0x0
r14    0x55ffd0f4138c
r15    0x0
rip    0x7f90b638e438
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```
something seems very buggy on my vserver :-(

**Comment by farhatahmad** [comment]
Sounds like a bugged out machine then. I suggest you try installing it on a new machine
