### ISSUE TITLE
BBB room not starting

### ISSUE THREAD

**Issue by WilliamCou** [bigbluebutton/greenlight#2018]
After a new, fresh manual, customize BBB, greenlight installation via the BBB documentan my installation has an issue. When I start a room with greenlight, nothing happens. The page loads for a second, but no error message. I tested a lot and I don't know how to debug this further.

start a room (via greenlight) doesn't work:

greenlight/logs/production.log

```
INFO: [59b29a03-c1fa-4000-884f-e89c91abaa29] Support: bbb@replacename.com is starting room adm-9oo-wdr-bi5
INFO: [54a097ef-f093-4341-b2b6-efd004eb046d] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=35.70 view=20.11 db=5.04 host=greenlight
INFO: [6ad5b39f-e54e-4383-b0c9-69b0bb24c395] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=28.72 view=21.64 db=0.97 host=greenlight
INFO: [bddbd322-4964-409e-9619-dfa3b1a0b802] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=23.56 view=17.09 db=0.87 host=greenlight
INFO: [59b29a03-c1fa-4000-884f-e89c91abaa29] [ActiveJob] Enqueued NotifyUserWaitingJob (Job ID: 11f39e09-3e3f-42c5-b9de-aba95adbdde3) to Async(default) at 2020-08-17 08:14:39 UTC with arguments: #<GlobalID:0x00005580bd188420 @uri=#<URI::GID gid://greenlight/Room/1>>
INFO: [59b29a03-c1fa-4000-884f-e89c91abaa29] method=POST path=/b/adm-9oo-wdr-bi5/start format=html controller=RoomsController action=start status=302 duration=304.07 view=0.00 db=10.40 location=https://bbbg.replacename.com/bigbluebutton/api/join host=greenlight
INFO: [44c891ea-f3e8-4e81-80c7-07c6b397471c] method=GET path=/b/ format=html controller=MainController action=index status=302 duration=8.11 view=0.00 db=1.57 location=https://bbbg.replacename.com/b/adm-9oo-wdr-bi5 host=greenlight
INFO: [1ce23d1c-c2ca-4d45-b3a4-6e901ec255b1] method=GET path=/b/adm-9oo-wdr-bi5 format=html controller=RoomsController action=show status=200 duration=82.47 view=25.55 db=5.55 host=greenlight
INFO: [ActiveJob] [NotifyUserWaitingJob] [11f39e09-3e3f-42c5-b9de-aba95adbdde3] Performing NotifyUserWaitingJob (Job ID: 11f39e09-3e3f-42c5-b9de-aba95adbdde3) from Async(default) with arguments: #<GlobalID:0x00005580baac10a8 @uri=#<URI::GID gid://greenlight/Room/1>>
INFO: [ActiveJob] [NotifyUserWaitingJob] [11f39e09-3e3f-42c5-b9de-aba95adbdde3] Performed NotifyUserWaitingJob (Job ID: 11f39e09-3e3f-42c5-b9de-aba95adbdde3) from Async(default) in 0.17ms
```

------

create a room: (works)

```
INFO: [6f3894a3-dc03-4618-81d2-9e356336d2e3] Support: bbb@replacename.com has created a new room adm-zut-jvv-gqb.
INFO: [6f3894a3-dc03-4618-81d2-9e356336d2e3] method=POST path=/b/ format=html controller=RoomsController action=create status=302 duration=221.81 view=0.00 db=63.78 location=https://bbbg.replacename.com/b/adm-zut-jvv-gqb host=greenlight
INFO: [15201769-20a7-40d0-aec5-1cce30634b9a] method=GET path=/b/adm-zut-jvv-gqb format=html controller=RoomsController action=show status=200 duration=76.09 view=22.42 db=4.71 host=greenlight
```
                                             
------

linux@bbbg:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

```
Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
```

------

> bbb-conf --status

```
linux@bbbg:~/greenlight# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

------

openssl s_client -connect bbbg.replacename.com:443
```
    00a0 - b5 56 14 9c 6a 2f 12 24-86 4c 05 87 e2 92 17 2b   .V..j/.$.L.....+

    Start Time: 1597652244
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```
...

**Comment by farhatahmad** [comment]
Can you provide more details of what is actually happening?

> nothing happens.

After you click the start button, does it just sit on the same page?

**Comment by WilliamCou** [comment]
Yes, it stays on the same page and nothing changes on the page, but the Firefox tab icon animation for loading shows activity for a second.

This is the greenlightlog, when I click the start button
greenlight/logs/production.log

```
INFO: [59b29a03-c1fa-4000-884f-e89c91abaa29] Support: bbb@replacename.com is starting room adm-9oo-wdr-bi5
INFO: [54a097ef-f093-4341-b2b6-efd004eb046d] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=35.70 view=20.11 db=5.04 host=greenlight
INFO: [6ad5b39f-e54e-4383-b0c9-69b0bb24c395] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=28.72 view=21.64 db=0.97 host=greenlight
INFO: [bddbd322-4964-409e-9619-dfa3b1a0b802] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=23.56 view=17.09 db=0.87 host=greenlight
INFO: [59b29a03-c1fa-4000-884f-e89c91abaa29] [ActiveJob] Enqueued NotifyUserWaitingJob (Job ID: 11f39e09-3e3f-42c5-b9de-aba95adbdde3) to Async(default) at 2020-08-17 08:14:39 UTC with arguments: #<GlobalID:0x00005580bd188420 @uri=#<URI::GID gid://greenlight/Room/1>>
INFO: [59b29a03-c1fa-4000-884f-e89c91abaa29] method=POST path=/b/adm-9oo-wdr-bi5/start format=html controller=RoomsController action=start status=302 duration=304.07 view=0.00 db=10.40 location=https://bbbg.replacename.com/bigbluebutton/api/join host=greenlight
INFO: [44c891ea-f3e8-4e81-80c7-07c6b397471c] method=GET path=/b/ format=html controller=MainController action=index status=302 duration=8.11 view=0.00 db=1.57 location=https://bbbg.replacename.com/b/adm-9oo-wdr-bi5 host=greenlight
INFO: [1ce23d1c-c2ca-4d45-b3a4-6e901ec255b1] method=GET path=/b/adm-9oo-wdr-bi5 format=html controller=RoomsController action=show status=200 duration=82.47 view=25.55 db=5.55 host=greenlight
INFO: [ActiveJob] [NotifyUserWaitingJob] [11f39e09-3e3f-42c5-b9de-aba95adbdde3] Performing NotifyUserWaitingJob (Job ID: 11f39e09-3e3f-42c5-b9de-aba95adbdde3) from Async(default) with arguments: #<GlobalID:0x00005580baac10a8 @uri=#<URI::GID gid://greenlight/Room/1>>
INFO: [ActiveJob] [NotifyUserWaitingJob] [11f39e09-3e3f-42c5-b9de-aba95adbdde3] Performed NotifyUserWaitingJob (Job ID: 11f39e09-3e3f-42c5-b9de-aba95adbdde3) from Async(default) in 0.17ms


```

**Comment by WilliamCou** [comment]
Yes, it stays on the same page and nothing changes on the page, but the Firefox tab icon animation for loading shows activity for a second.

This is the greenlightlog, when I click the start button
greenlight/logs/production.log

```
INFO: [59b29a03-c1fa-4000-884f-e89c91abaa29] Support: bbb@replacename.com is starting room adm-9oo-wdr-bi5
INFO: [54a097ef-f093-4341-b2b6-efd004eb046d] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=35.70 view=20.11 db=5.04 host=greenlight
INFO: [6ad5b39f-e54e-4383-b0c9-69b0bb24c395] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=28.72 view=21.64 db=0.97 host=greenlight
INFO: [bddbd322-4964-409e-9619-dfa3b1a0b802] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=23.56 view=17.09 db=0.87 host=greenlight
INFO: [59b29a03-c1fa-4000-884f-e89c91abaa29] [ActiveJob] Enqueued NotifyUserWaitingJob (Job ID: 11f39e09-3e3f-42c5-b9de-aba95adbdde3) to Async(default) at 2020-08-17 08:14:39 UTC with arguments: #<GlobalID:0x00005580bd188420 @uri=#<URI::GID gid://greenlight/Room/1>>
INFO: [59b29a03-c1fa-4000-884f-e89c91abaa29] method=POST path=/b/adm-9oo-wdr-bi5/start format=html controller=RoomsController action=start status=302 duration=304.07 view=0.00 db=10.40 location=https://bbbg.replacename.com/bigbluebutton/api/join host=greenlight
INFO: [44c891ea-f3e8-4e81-80c7-07c6b397471c] method=GET path=/b/ format=html controller=MainController action=index status=302 duration=8.11 view=0.00 db=1.57 location=https://bbbg.replacename.com/b/adm-9oo-wdr-bi5 host=greenlight
INFO: [1ce23d1c-c2ca-4d45-b3a4-6e901ec255b1] method=GET path=/b/adm-9oo-wdr-bi5 format=html controller=RoomsController action=show status=200 duration=82.47 view=25.55 db=5.55 host=greenlight
INFO: [ActiveJob] [NotifyUserWaitingJob] [11f39e09-3e3f-42c5-b9de-aba95adbdde3] Performing NotifyUserWaitingJob (Job ID: 11f39e09-3e3f-42c5-b9de-aba95adbdde3) from Async(default) with arguments: #<GlobalID:0x00005580baac10a8 @uri=#<URI::GID gid://greenlight/Room/1>>
INFO: [ActiveJob] [NotifyUserWaitingJob] [11f39e09-3e3f-42c5-b9de-aba95adbdde3] Performed NotifyUserWaitingJob (Job ID: 11f39e09-3e3f-42c5-b9de-aba95adbdde3) from Async(default) in 0.17ms


```

**Comment by WilliamCou** [comment]
And I tried different browsers.

**Comment by farhatahmad** [comment]
Are you still having this problem?

**Comment by mahdimahrooghi** [comment]
I have this problem too :(

**Comment by hostbbb** [comment]
this is a 2020 issue?  you are probably on GL v3.  you need to provide some logs from your server, and the client.  does this happen to you or everybody, versions etc.

**Comment by JeanPluzo** [comment]
> this is a 2020 issue? you are probably on GL v3. you need to provide some logs from your server, and the client. does this happen to you or everybody, versions etc.

Or better yet: open another issue since this one is closed and will most likely not show up in many places.

**Comment by smvelo** [comment]
How did you resolve the issue? I also have a problem:

**Error:**
"The action can't be completed. Please try again."

**web console error:**
main-a138d3c36fdc208…9c4ef2a6fc7d5.js:12 
Np {message: 'Request failed with status code 400', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_BAD_REQUEST"
config
: 
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 30000, …}
message
: 
"Request failed with status code 400"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 30000, withCredentials: false, upload: XMLHttpRequestUpload, …}
response
: 
{data: {…}, status: 400, statusText: '', headers: Pp, config: {…}, …}
stack
: 
"AxiosError: Request failed with status code 400\n    at ZP (https://example.com/assets/main-a138d3c36fdc20846c1bbb8c59d6f3ae9822b878cb9d0bbc91b9c4ef2a6fc7d5.js:15:1041)\n    at XMLHttpRequest.m (https://meetings.softmeet.co.za/assets/main-a138d3c36fdc20846c1bbb8c59d6f3ae9822b878cb9d0bbc91b9c4ef2a6fc7d5.js:15:4188)"
[[Prototype]]
:
