### ISSUE TITLE
[Docker] [First-Install] Error during failsafe response: Couldn't find Room

### ISSUE THREAD

**Issue by h8h** [bigbluebutton/greenlight#2071]
Hi,

Fireing up docker-compose for the first time fresh database and so on I run into a problem on the first login attempt (https://domain.tld/b/), getting a `500 Internal Server Error` and in the logs I get: 

`Error during failsafe response: Couldn't find Room with [WHERE "rooms"."deleted" = $1 AND "rooms"."uid" = $2]`.

Looking in the table "rooms" there are no entries. Is this normal for a fresh installation? If I try to run `docker exec .... bundle exec rake room:four` there is no output and still no entries in the table.

![image001](https://user-images.githubusercontent.com/953856/92232845-85d15f00-eeaf-11ea-892e-b644425748af.png)

The corresponding docker-compose file:
![image002](https://user-images.githubusercontent.com/953856/92232849-8833b900-eeaf-11ea-888b-a3ddb978ce25.png)

Sorry for the pictures but powershell.exe mess up with the output. B.t.w. I only use powershell for ssh access. Docker is running on a linux host (ubuntu 18.04)

**Comment by farhatahmad** [comment]
How did you create the user you're using to sign in? Was it through the sign up page? Can you try signing up with a different user and seeing if the issue persists?

**Comment by Tecumtha** [comment]
I have the same Problem.

Fresh installation and adding a user with the command:

docker exec greenlight-v2 bundle exec rake user:create["xxx","xxxxx","xxxxx","admin"]

500 Internal Server Error

```
greenlight-v2 | * Listening on tcp://0.0.0.0:80
greenlight-v2 |  Use Ctrl-C to stop
greenlight-v2 |  Error during failsafe response: Couldn't find Room with [WHERE "rooms"."deleted" = $1 AND "rooms"."uid" = $2]
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation/finder_methods.rb:343:in `raise_record_not_found_exception!'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation/finder_methods.rb:109:in `take!'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/relation/finder_methods.rb:89:in `find_by!'
greenlight-v2 |   /usr/src/app/app/controllers/rooms_controller.rb:354:in `find_room'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `each'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `invoke_before'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `block in instrument'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `instrument'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:134:in `process'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.3/lib/action_view/rendering.rb:32:in `process'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:191:in `dispatch'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:252:in `dispatch'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `each'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `serve'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by h8h** [comment]
Yep. As @Tecumtha said. I've also created the user using the cli.

If I figured it out correctly, it crashs before login, it doesn't matter what you're login credentials are.

**Comment by farhatahmad** [comment]
I just did a fresh install, created an admin, and successfully signed in. What version of Greenlight are you running (you can see the version at the bottom of any Greenlight page)

**Comment by altsalt** [comment]
I am having this issue, see log and initial report here: https://github.com/alangecker/bigbluebutton-docker/issues/57#issuecomment-715799768

**Comment by mghadam** [comment]
I had the same issue. I was using bbb-docker and was forwarding requests from apache to greenlight vm (10.7.7.1:5000) directly which is wrong. It was resolved when I forwarded requests to 127.0.0.1:8080 according to [the docs](https://github.com/alangecker/bigbluebutton-docker/blob/v2.2.x/docs/existing-web-server.md#integration-with-apache)

**Comment by tpo** [comment]
Same problem like https://github.com/bigbluebutton/greenlight/issues/2071#issue-693053899 .

I've tried with https://github.com/alangecker/bigbluebutton-docker/tree/v2.2.x and also with https://github.com/alangecker/bigbluebutton-docker/tree/v2.3.x . Followed the instructions to the letter.

When I check in line /usr/src/app/app/controllers/rooms_controller.rb what params[:room_uid] is:

      def find_room
         File.open("/tmp/foobar", 'w') { |file| file.write( params[:room_uid]) }
         @room = Room.includes(:owner).find_by!(uid: params[:room_uid])
  end

then I get 422. However there is no user with uid 422. There is only a user with uid 1 and that's admin. No idea where the the greenlight app is getting the uid 422 from.

**Comment by sjaiser** [comment]
I had the same issue - the problem in my case was the Referrer-Policy Header setting in the webserver nginx. Opening it up to same-origin solved the issue.

**Comment by mgolik** [comment]
I am having the same issue on clean install.
I've added some prints and got the same result as @tpo - room_uid is 422.
The whole "params" object:
`  {"utf8"=>"✓", "authenticity_token"=>"(...)", "session"=>{"email"=>"admin@example.com", "password"=>"administrator"}, "commit"=>"Zaloguj", "controller"=>"rooms", "action"=>"join", "room_uid"=>"422"}`
And find_room method fails with: 
`Error during failsafe response: Couldn't find Room with [WHERE "rooms"."deleted" = $1 AND "rooms"."uid" = $2]`

**Comment by mirhosting** [comment]
For anyone having this issue, check following solution:
Seems it related to a forced SSL setting in mod/nginx/bbb/greenlight.nginx

https://github.com/bigbluebutton/docker/blob/0dd3d9a0bc7ea3169e71f27246702f870a3607db/mod/nginx/bbb/greenlight.nginx#L12

`  proxy_set_header    X-Forwarded-Ssl on;`

if you are using (hopefully temporary) http schema to access greenlight, it will thrown following error:
```
HTTP Origin header (http://$yourgreenlighthost) didn't match request.base_url (https://$yourgreenlighthost)
method=POST path=/b/u/login format=html controller=SessionsController action=create status=422 error='ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken' duration=58.45 view=0.00 db=20.44 host=greenlight
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)
```

Somehow error status is not properly handled and results in a wrong db request. Also seems to me as a security issue to have error code passed as a variable to db.

**How to fix?**

Change to:
`  proxy_set_header    X-Forwarded-Ssl off;`

and restart greenlight container. 

Or (better) use https

**Comment by achromium** [comment]
@mirhosting changing header does not work.
I'm on latest docker install. Facing same issue. Pity.

**Comment by mirhosting** [comment]
> 
> 
> @mirhosting changing header does not work.
> I'm on latest docker install. Facing same issue. Pity.

Check logs, might be related to something else

**Comment by Alsterdetektive1** [comment]
I am facing the same error and trying to fix it. Like @mirhosting said, I shall enable debug for greenlight, but don't know how to do this. bbb-conf is not working and in .env file i cant declare a debug. So where to do this. I am using the docker build for bbb.
