### ISSUE TITLE
LDAP: `ActionController::RoutingError (No route matches [GET] "/auth/ldap"):`

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/greenlight#2227]
With Greenlight 2.7.6 setting up LDAP, after already having some users in the Greenlight user database, logging in with a test user *not* in the Greenlight DB, authentication seems to work, but the user is directed to a non-existing page, so a 404 error page is shown.

```
2020-10-24 17:07:24 +0000 - INFO: [4f8cfe4a-a917-480d-a1cb-b9513bba9ff0] Support: Auth user test@molgen.mpg.de is attempting to login. 
2020-10-24 17:07:24 +0000 - INFO: [4f8cfe4a-a917-480d-a1cb-b9513bba9ff0] Support: test@molgen.mpg.de has successfully logged in. 
2020-10-24 17:07:24 +0000 - INFO: [4f8cfe4a-a917-480d-a1cb-b9513bba9ff0] method=POST path=/b/auth/ldap format=html controller=SessionsController action=ldap status=302 duration=26.09 view=0.00 db=4.12 location=https://bigbluebutton.molgen.mpg.de/b/auth/ldap/ host=greenlight 
2020-10-24 17:07:24 +0000 - FATAL: [1eed04e3-ad1a-431d-927e-bc81212c8e0c]    
2020-10-24 17:07:24 +0000 - FATAL: [1eed04e3-ad1a-431d-927e-bc81212c8e0c] ActionController::RoutingError (No route matches [GET] "/auth/ldap"): 
2020-10-24 17:07:24 +0000 - FATAL: [1eed04e3-ad1a-431d-927e-bc81212c8e0c]    
2020-10-24 17:07:24 +0000 - FATAL: [1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:28:in `tagged'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `tagged'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:127:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/ssl.rb:74:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[1eed04e3-ad1a-431d-927e-bc81212c8e0c] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread' 
2020-10-24 17:07:24 +0000 - INFO: [1eed04e3-ad1a-431d-927e-bc81212c8e0c] method=GET path=/b/404 format=html controller=ErrorsController action=not_found status=404 duration=20.24 view=13.74 db=1.36 host=greenlight
```

As the menu is shown, the user can navigate to the start page.

**Comment by paulmenzel** [comment]
There is method `ldap` commented with `# GET /auth/ldap` in `app/controllers/sessions_controller.rb`:

https://github.com/bigbluebutton/greenlight/blob/620416f18ad4ed2ef374791a3187503df4e040c5/app/controllers/sessions_controller.rb#L124-L157

I added the line below to `config/routes.rb`

    get '/auth/ldap', to: 'sessions#ldap'

and now the LDAP user gets redirected to the start page (room).

```
2020-10-24 19:17:54 +0000 - INFO: [32cf293d-94b0-480e-a6da-2bbefb4a2c7a] Support: Auth user test@molgen.mpg.de is attempting to login. 
2020-10-24 19:17:54 +0000 - INFO: [32cf293d-94b0-480e-a6da-2bbefb4a2c7a] Support: test@molgen.mpg.de has successfully logged in. 
2020-10-24 19:17:54 +0000 - INFO: [32cf293d-94b0-480e-a6da-2bbefb4a2c7a] method=POST path=/b/auth/ldap format=html controller=SessionsController actio
n=ldap status=302 duration=77.72 view=0.00 db=11.49 location=https://bigbluebutton.molgen.mpg.de/b/mol-j1l-9uo-yfv host=greenlight 
2020-10-24 19:17:54 +0000 - INFO: [f0b0e154-df11-4365-b4c1-aafe19e361d2] method=GET path=/b/mol-j1l-9uo-yfv format=html controller=RoomsController act
ion=show status=200 duration=84.14 view=38.50 db=6.44 host=greenlight
```

I have no idea, what the intention of the routes are, so I am unable to formulate a good commit message, and, therefore, I am unable to create a merge/pull request.

**Comment by farhatahmad** [comment]
This is a small bug with the cookies - I've just fixed it and I'll include it in the next release. If you clear your cookies you should be okay

**Comment by kroerig** [comment]
I get the same behavior in 2.7.16.

`2021-01-17 20:06:05 +0000 - FATAL: [439f3305-268f-4bb5-88f0-50f98634370f]
2021-01-17 20:06:05 +0000 - FATAL: [439f3305-268f-4bb5-88f0-50f98634370f] ActionController::RoutingError (No route matches [GET] "/auth/ldap"):
2021-01-17 20:06:05 +0000 - FATAL: [439f3305-268f-4bb5-88f0-50f98634370f]
2021-01-17 20:06:05 +0000 - FATAL: [439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:28:in `tagged'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `tagged'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:127:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/ssl.rb:74:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[439f3305-268f-4bb5-88f0-50f98634370f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
`
