### ISSUE TITLE
Change postgres server to different host

### ISSUE THREAD

**Issue by bumblebee87kfu** [bigbluebutton/greenlight#2246]
Hello everyone,

I have a simple question: Is it possible to connect Greenlight to a postgres server on a different host instead of the docker one?

I tried to connect from docker host system to the database and it worked fine with the given credentials. I changed the DB_HOST, DB_USER and DB_PASSWORD in greenlights .env but when I start the container it fails on "Database initialization". 

I get this error:
```
Attaching to greenlight-v2
greenlight-v2 | curl: (52) Empty reply from server
greenlight-v2 | bundler: failed to load command: rake (/usr/src/app/vendor/bundle/ruby/2.5.0/bin/rake) Bundler::GemNotFound: Could not find concurrent-ruby-1.1.7 in any of the sources /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:91:in `block in materialize' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `map!' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `materialize' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:171:in `specs' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:238:in `specs_for' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:227:in `requested_specs' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:108:in `block in definition_method' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:20:in `setup' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup' /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>' /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require' /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 | >>> Database initialization
greenlight-v2 | Bundler::GemNotFound: Could not find concurrent-ruby-1.1.7 in any of the sources
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:91:in `block in materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `map!'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:171:in `specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:238:in `specs_for'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:227:in `requested_specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:108:in `block in definition_method'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:20:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 | bundler: failed to load command: rake (/usr/src/app/vendor/bundle/ruby/2.5.0/bin/rake)
greenlight-v2 | bundler: failed to load command: rake (/usr/src/app/vendor/bundle/ruby/2.5.0/bin/rake)
greenlight-v2 | Bundler::GemNotFound: Could not find concurrent-ruby-1.1.7 in any of the sources
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:91:in `block in materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `map!'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:171:in `specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:238:in `specs_for'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:227:in `requested_specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:108:in `block in definition_method'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:20:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 | bundler: failed to load command: puma (/usr/src/app/vendor/bundle/ruby/2.5.0/bin/puma)
greenlight-v2 | Bundler::GemNotFound: Could not find concurrent-ruby-1.1.7 in any of the sources
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:91:in `block in materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `map!'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/spec_set.rb:85:in `materialize'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:171:in `specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:238:in `specs_for'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:227:in `requested_specs'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:108:in `block in definition_method'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:20:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
greenlight-v2 |   /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```
.env looks like this:
```

DB_ADAPTER=postgresql
DB_HOST=<IP-ADDRESS>
DB_NAME=greenlight_production
DB_USERNAME=<USER>
DB_PASSWORD=<PASSWORD>
```

**Comment by farhatahmad** [comment]
Hmm that error doesn't seem right. Something else is going on. If you revert those back to the original value, does everything work?
