### ISSUE TITLE
Greenlight Error 500 when regestering/logging in via O365

### ISSUE THREAD

**Issue by SDanteB** [bigbluebutton/greenlight#2264]
Hello,

I've recently set up a BigBlueButton-Server with Greenlight, so the users would be able to register via O365.

Visiting the website https://bbb.domain.com/b shows the correct option to login and register. 

![grafik](https://user-images.githubusercontent.com/72793320/98260215-56a89e00-1f83-11eb-8506-d218f1d941ac.png)

Sadly after registration, I'm forwarded to a page with an error depicting 500

![grafik](https://user-images.githubusercontent.com/72793320/98260502-b3a45400-1f83-11eb-8db7-7d09c140553e.png)

The certificate authentication in Microsoft Azure is set to login to any organisation (just for testing) and a restriction has not been set in the .env

This is my first time using Linux and therefore I'm not quite sure what to do or where to look.

Thank you in advance.

Dante

**Comment by farhatahmad** [comment]
I'll need some logs to see why thats happening - Can you paste some lines from `~/greenlight/log/production.log` right after replicating the 500 issue?

**Comment by SDanteB** [comment]
Hello Ahmad,

I hope you are doing well. Thank you for your reply.

<details>
<summary>Results from production.log</summary>

INFO: [95eccbea-a369-4d77-a337-f1581cc4e233] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=12.70 view=8.70 db=0.63 host=greenlight
INFO: [6ed3f698-7d3d-40a0-9e70-456137f83955] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=19.87 view=9.42 db=3.84 host=greenlight
INFO: [22556962-e052-4d2a-ba6b-33f33310dbfe] method=GET path=/b/signup format=html controller=SessionsController action=new status=200 duration=14.82 view=10.69 db=0.68 host=greenlight
INFO: [dd07b364-9662-4748-bb8b-469d08b82487] (office365) Setup endpoint detected, running now.
INFO: [dd07b364-9662-4748-bb8b-469d08b82487] (office365) Request phase initiated.
INFO: [a2365235-69d2-48e2-affc-ecb495712391] (office365) Setup endpoint detected, running now.
INFO: [a2365235-69d2-48e2-affc-ecb495712391] (office365) Request phase initiated.
INFO: [16f5870b-bf9c-447c-b23e-bac51d071a9b] (office365) Setup endpoint detected, running now.
INFO: [16f5870b-bf9c-447c-b23e-bac51d071a9b] (office365) Callback phase initiated.
FATAL: [16f5870b-bf9c-447c-b23e-bac51d071a9b]
FATAL: [16f5870b-bf9c-447c-b23e-bac51d071a9b] Faraday::ConnectionFailed (Failed to open TCP connection to login.microsoftonline.com:443 (getaddrinfo: Try again)):
FATAL: [16f5870b-bf9c-447c-b23e-bac51d071a9b]
FATAL: [16f5870b-bf9c-447c-b23e-bac51d071a9b] /usr/local/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] /usr/local/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] /usr/local/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] /usr/local/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] /usr/local/lib/ruby/2.5.0/net/http.rb:935:in `connect'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] /usr/local/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] /usr/local/lib/ruby/2.5.0/net/http.rb:909:in `start'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:152:in `request_via_request_method'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:137:in `request_with_wrapped_block'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:128:in `perform_request'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:70:in `block in call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/adapter.rb:60:in `connection'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:68:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/request/url_encoded.rb:25:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/oauth2-1.4.4/lib/oauth2/client.rb:99:in `request'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/oauth2-1.4.4/lib/oauth2/client.rb:147:in `get_token'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/oauth2-1.4.4/lib/oauth2/strategy/auth_code.rb:30:in `get_token'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/omniauth-oauth2-1.5.0/lib/omniauth/strategies/oauth2.rb:89:in `build_access_token'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/omniauth-oauth2-1.5.0/lib/omniauth/strategies/oauth2.rb:73:in `callback_phase'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:238:in `callback_call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:189:in `call!'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/builder.rb:45:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/ssl.rb:74:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/ssl.rb:74:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[16f5870b-bf9c-447c-b23e-bac51d071a9b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
INFO: [16f5870b-bf9c-447c-b23e-bac51d071a9b] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=14.30 view=10.10 db=0.65 host=greenlight


</details>

Thank you very much.

Dante

**Comment by farhatahmad** [comment]
> Faraday::ConnectionFailed (Failed to open TCP connection to login.microsoftonline.com:443 (getaddrinfo: Try again)):

Seems like your machine is unable to make outgoing requests - I would try taking a look at the VMs configuration

**Comment by SDanteB** [comment]
Hello Ahmad,

I'll check the Server and corresponding Firewall.

Thank you for your help.

Dante
