### ISSUE TITLE
"Error during failsafe response: Couldn't find Room" Error in production.log after POST to Greenlight

### ISSUE THREAD

**Issue by wolbernd** [bigbluebutton/greenlight#2299]
After a recent Pentest which also included our Greenlight-Server I found some strange entries in the production.log and investigated a bit. The Pentest itself found no problems. 
I found out that if you make a POST-Request to any Greenlight URL you get a long Stacktrace in your production log:
```
Error during failsafe response: Couldn't find Room with [WHERE "rooms"."deleted" = $1 AND "rooms"."uid" = $2]
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/relation/finder_methods.rb:343:in `raise_record_not_found_exception!'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/relation/finder_methods.rb:109:in `take!'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/relation/finder_methods.rb:89:in `find_by!'
  /usr/src/app/app/controllers/rooms_controller.rb:352:in `find_room'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `each'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:134:in `process'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.4/lib/action_view/rendering.rb:32:in `process'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:191:in `dispatch'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:252:in `dispatch'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:34:in `serve'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:52:in `block in serve'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `each'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `serve'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:840:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:28:in `tagged'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `tagged'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:127:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

This by itself is not a problem but I'm not sure wether Greenlight should check anything regarding rooms after getting a POST-Request from an unauthenticated user. 

Steps to reproduce:
* Get current version of Greenlight (I used the docker-compose variant)
* Create a minimal .env file
* Start Greenlight
* Do a POST Request. e.g with curl: `curl -d '' http://localhost:5000/b/`
* See above stacktrace in greenlight log or docker-compose output

**Comment by farhatahmad** [comment]
This isn't really a problem since there aren't any side effects from this other than a couple extra log files. Going to close this as this isn't really a priority to fix at the moment (or anytime soon)

**Comment by crosscodr** [comment]
Hi @farhatahmad, I had this issue today in greenlight 2.9.0.
It can also be triggered by calling non-existing urls, like https://<greenlight.tld>/assets/sdbsearch.cgi.
This is done by security-scanners and should not trigger a "FATAL" error in production.log, since it makes it more difficult to distinguish between _real_ FATAL errors and such minor fails, which should be handled otherwise, imho.
Also the production.log will be spammed with such useless entries, so that searching for real errors is made difficult.
