### ISSUE TITLE
Greenlight 2.7.11 - Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/greenlight#2357]
Hi :-)

we get repeatedly the following error in a fresh install with bbb-install.sh
SAFE_HOSTS is set correctly.

```
2020-12-10 15:40:23 +0000 - INFO: [39c41c28-d902-4d71-84c3-f6fe893c7898] method=GET path=/b/bdb-vn6-92y-xbt format=html controller=RoomsController action=show status=200 duration=51.80 view=13.12 db=1.17 host=greenlight 
2020-12-10 15:41:50 +0000 - WARN: [8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] Can't verify CSRF token authenticity. 
2020-12-10 15:41:50 +0000 - INFO: [8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] method=POST path=/b/bdb-2ck-9hl-dky/start format=html controller=RoomsController action=start status=422 error='ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken' duration=5.79 view=0.00 db=0.51 host=greenlight 
2020-12-10 15:41:50 +0000 - FATAL: [8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b]    
2020-12-10 15:41:50 +0000 - FATAL: [8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken): 
2020-12-10 15:41:50 +0000 - FATAL: [8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b]    
2020-12-10 15:41:50 +0000 - FATAL: [8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `each'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:134:in `process'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.4.4/lib/action_view/rendering.rb:32:in `process'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:191:in `dispatch'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:252:in `dispatch'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:34:in `serve'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:52:in `block in serve'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `each'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `serve'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:840:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/builder.rb:45:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/cookies.rb:670:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:28:in `tagged'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `tagged'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:127:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/ssl.rb:74:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[8e076c3d-692d-4ff8-9cd4-d3ef5976ea4b] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by farhatahmad** [comment]
Can you try a different browser? Nothings changed here so I'm not sure why it would start throwing a CSRF error all of a sudden

**Comment by lonesomewalker** [comment]
Unfortunately this is independent from the browser.
Tried Chrome latest, Firefox latest, Edge latest.
FF also on Linux and Mac. :-/

**Comment by farhatahmad** [comment]
We used to have issues with this previously but mostly on the join method and not the start. We were never really able to pinpoint what the exact issue was. I'll dig into this a bit more but we aren't currently seeing this issue with other deployments. As far as I can tell, it has a lot to do with the user and how their browser is set up

**Comment by lonesomewalker** [comment]
Okay, we'll also give this some days to watch. This happens not all the time, but sometimes the log is quite hefty... :-/
Closed :-)
