### ISSUE TITLE
500 error with google auth

### ISSUE THREAD

**Issue by lds-lds** [bigbluebutton/greenlight#2396]
Hello
I just updated bbb and since then I have this error when connecting via google auth : `FATAL: [732ffdc4-ff28-43ee-855a-d3816c87f090] JWT::InvalidIatError (Invalid iat):`

the full trace below

```
2020-12-29 11:17:28 +0000 - INFO: [d98f3572-8009-4b7c-b50e-38c40d8f9c52] (google) Setup endpoint detected, running now. 
2020-12-29 11:17:28 +0000 - INFO: [d98f3572-8009-4b7c-b50e-38c40d8f9c52] (google) Request phase initiated. 
2020-12-29 11:17:28 +0000 - INFO: [16dfbb60-4448-4d6d-b845-70fbf891d2aa] (google) Setup endpoint detected, running now. 
2020-12-29 11:17:28 +0000 - INFO: [16dfbb60-4448-4d6d-b845-70fbf891d2aa] (google) Request phase initiated. 
2020-12-29 11:17:28 +0000 - INFO: [4ef02cdd-9088-4bb6-b465-e68a20784d07] (google) Setup endpoint detected, running now. 
2020-12-29 11:17:28 +0000 - INFO: [4ef02cdd-9088-4bb6-b465-e68a20784d07] (google) Callback phase initiated. 
2020-12-29 11:17:29 +0000 - FATAL: [4ef02cdd-9088-4bb6-b465-e68a20784d07]    
2020-12-29 11:17:29 +0000 - FATAL: [4ef02cdd-9088-4bb6-b465-e68a20784d07] JWT::InvalidIatError (Invalid iat): 
2020-12-29 11:17:29 +0000 - FATAL: [4ef02cdd-9088-4bb6-b465-e68a20784d07]    
2020-12-29 11:17:29 +0000 - FATAL: [4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/jwt-2.2.1/lib/jwt/verify.rb:48:in `verify_iat'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/jwt-2.2.1/lib/jwt/verify.rb:15:in `block (2 levels) in singleton class'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/jwt-2.2.1/lib/jwt/verify.rb:22:in `block in verify_claims'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/jwt-2.2.1/lib/jwt/verify.rb:20:in `each'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/jwt-2.2.1/lib/jwt/verify.rb:20:in `verify_claims'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-google-oauth2-0.7.0/lib/omniauth/strategies/google_oauth2.rb:69:in `block in <class:GoogleOauth2>'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:109:in `instance_eval'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:109:in `block in compile_stack'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:108:in `each'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:108:in `inject'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:108:in `compile_stack'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:102:in `extra_stack'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:344:in `extra'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:351:in `auth_hash'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:372:in `callback_phase'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-oauth2-1.5.0/lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:238:in `callback_call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:189:in `call!'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.1/lib/omniauth/builder.rb:45:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/cookies.rb:670:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:28:in `tagged'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `tagged'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:127:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/ssl.rb:74:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[4ef02cdd-9088-4bb6-b465-e68a20784d07] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread' 

```

**Comment by lds-lds** [comment]
ntpdate pool.ntp.org seems to solve the problem
