### ISSUE TITLE
OpenID Connect - AttrMissing ('host' required.)

### ISSUE THREAD

**Issue by saul-avikar** [bigbluebutton/greenlight#2761]
When I configure OpenID Connect for Greenlight I get an internal server error on the login page. Logs refer to a missing "host" attribute.

The environment file refers to this link for "in-depth steps on setting up a OpenID Connect Login Provider" but the section appears to be missing: https://docs.bigbluebutton.org/greenlight/gl-config.html#openid-connect.

### Front End Console Logs
```
Uncaught SyntaxError: redeclaration of let require
```

### Greenlight Logs
```
(openid_connect) Setup endpoint detected, running now. 
(openid_connect) Request phase initiated. 

AttrRequired::AttrMissing ('host' required.): 

vendor/bundle/ruby/2.7.0/gems/attr_required-1.0.1/lib/attr_required.rb:59:in `attr_missing!'
vendor/bundle/ruby/2.7.0/gems/openid_connect-1.2.0/lib/openid_connect/discovery/provider/config/resource.rb:16:in `initialize'
vendor/bundle/ruby/2.7.0/gems/openid_connect-1.2.0/lib/openid_connect/discovery/provider/config.rb:7:in `new'
vendor/bundle/ruby/2.7.0/gems/openid_connect-1.2.0/lib/openid_connect/discovery/provider/config.rb:7:in `discover!'
vendor/bundle/ruby/2.7.0/gems/omniauth_openid_connect-0.3.5/lib/omniauth/strategies/openid_connect.rb:97:in `config'
vendor/bundle/ruby/2.7.0/gems/omniauth_openid_connect-0.3.5/lib/omniauth/strategies/openid_connect.rb:196:in `discover!'
vendor/bundle/ruby/2.7.0/gems/omniauth_openid_connect-0.3.5/lib/omniauth/strategies/openid_connect.rb:102:in `request_phase'
vendor/bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:226:in `request_call'
vendor/bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:188:in `call!'
vendor/bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
vendor/bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/builder.rb:45:in `call'
vendor/bundle/ruby/2.7.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/cookies.rb:670:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:98:in `run_callbacks'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
vendor/bundle/ruby/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `block in call'
vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
vendor/bundle/ruby/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/request_id.rb:27:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/static.rb:127:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/ssl.rb:74:in `call'
vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/configuration.rb:228:in `call'
vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/server.rb:718:in `handle_request'
vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/server.rb:472:in `process_client'
vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/server.rb:328:in `block in run'
vendor/bundle/ruby/2.7.0/gems/puma-4.3.8/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=31.27 view=21.52 db=1.62 host=greenlight 
```

**Comment by saul-avikar** [comment]
The **.env** file required `OPENID_CONNECT_ISSUER` field to be in the form `https://example.com` instead of `example.com` unlike the HD fields.
