### ISSUE TITLE
postgresql passwords with special chars failure

### ISSUE THREAD

**Issue by RokkuCode** [bigbluebutton/greenlight#2841]
with #2113 generated passwords contain special chars "/ +". these are not usable with greenlight and postgresql

testpassword
```0vFhWvISO3+49eKEN+egYEdhIq3Rt6XZ```

.env
```
DB_PASSWORD=0vFhWvISO3+49eKEN+egYEdhIq3Rt6XZ
```

docker-compose.yml
```
- POSTGRES_PASSWORD=0vFhWvISO3+49eKEN+egYEdhIq3Rt6XZ
```

results:
```
greenlight-v2 | FATAL: password authentication failed for user "postgres" Couldn't create 'greenlight_production' database. Please check your configuration. rake aborted! PG::ConnectionBad: FATAL: password authentication failed for user "postgres" /usr/src/app/vendor/bundle/ruby/2.7.0/gems/pg-0.21.0/lib/pg.rb:56:in `initialize' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/pg-0.21.0/lib/pg.rb:56:in `new' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/pg-0.21.0/lib/pg.rb:56:in `connect' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:118:in `retrieve_connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:90:in `connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:119:in `create' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:313:in `each' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:138:in `create_current' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <main>' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>' /usr/local/bin/bundle:23:in `load' /usr/local/bin/bundle:23:in `<main>' Tasks: TOP => db:create (See full trace by running task with --trace)
```

after removing the special chars everything works again.

For security concerns: Passwords should work containing special chards. So falling back to [a-zA-Z0-9] is not a good idea. This should improved

**Comment by farhatahmad** [comment]
Have you tried wrapping it in quotes?

**Comment by l00ptr** [comment]
I can't reproduce this problem. I tested with this password 0vFhWvISO3+49eKEN+egYEdhIq3Rt6XZ without quoting and its works.

@RokkuCode could you share some information about the version of greenlight and postgres you use ?

Best regards,
J
