### ISSUE TITLE
Problem in create admin account greenlight

### ISSUE THREAD

**Issue by mchoopani** [bigbluebutton/greenlight#2911]
Hi.
I want to create an administrator account with docker:
```
docker exec greenlight-v2 bundle exec rake admin:create
```
but i get this error:
```
rake aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'email_verified' for User.
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activemodel-5.2.6/lib/active_model/attribute_assignment.rb:53:in `_assign_attribute'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activemodel-5.2.6/lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activemodel-5.2.6/lib/active_model/attribute_assignment.rb:43:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activemodel-5.2.6/lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/attribute_assignment.rb:23:in `_assign_attributes'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activemodel-5.2.6/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/core.rb:315:in `initialize'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/inheritance.rb:66:in `new'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/inheritance.rb:66:in `new'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/persistence.rb:35:in `create'
/usr/src/app/lib/tasks/user.rake:42:in `block (2 levels) in <main>'
/usr/src/app/lib/tasks/administrator.rake:8:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => user:create
(See full trace by running task with --trace)
```
how can if fix it? (for installing greenlight, i follow [customize ](https://docs.bigbluebutton.org/greenlight/gl-customize.html)section.)

**Comment by mchoopani** [comment]
I remove greenlight folder and first install greenlight in install mode, then switch it to cusomize mode, and solved.
Thanks
