### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Ciangi** [bigbluebutton/greenlight#316]
```
Processing by RoomsController#show as HTML
  Parameters: {"room_uid"=>"b"}
Completed 500 Internal Server Error in 98ms (ActiveRecord: 3.3ms)



ActiveRecord::StatementInvalid (Could not find table 'rooms'):

app/controllers/rooms_controller.rb:164:in `find_room'
Processing by ErrorsController#internal_error as HTML
  Parameters: {"room_uid"=>"b"}
  Rendering errors/internal_error.html.erb within layouts/application
  Rendered errors/internal_error.html.erb within layouts/application (51.2ms)
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT ?  [["LIMIT", 1]]
  Rendered shared/_header.html.erb (43.6ms)
Completed 500 Internal Server Error in 809ms (ActiveRecord: 0.8ms)


Error during failsafe response: SQLite3::SQLException: no such table: users: SELECT  "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT ?
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/sqlite3_adapter.rb:208:in `block in exec_query'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/sqlite3_adapter.rb:193:in `exec_query'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/querying.rb:39:in `find_by_sql'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/relation.rb:706:in `exec_queries'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/relation.rb:583:in `load'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/relation.rb:260:in `records'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/relation/finder_methods.rb:527:in `find_take'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/relation/finder_methods.rb:100:in `take'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/relation/finder_methods.rb:78:in `find_by'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/querying.rb:7:in `find_by'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/core.rb:187:in `find_by'
  /root/greenlight/app/helpers/sessions_helper.rb:48:in `current_user'
  /root/greenlight/app/views/shared/_header.html.erb:19:in `_app_views_shared__header_html_erb__1435069524742813948_70023392995880'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/template.rb:159:in `block in render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:166:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/template.rb:354:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/template.rb:157:in `render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:164:in `block in instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:164:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/partial_renderer.rb:310:in `render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/renderer.rb:47:in `render_partial'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/helpers/rendering_helper.rb:35:in `render'
  /root/greenlight/app/views/layouts/application.html.erb:38:in `_app_views_layouts_application_html_erb__2539455357519078626_70023371404740'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/template.rb:159:in `block in render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:166:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/template.rb:354:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/template.rb:157:in `render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/template_renderer.rb:14:in `render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/renderer.rb:42:in `render_template'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/renderer/renderer.rb:23:in `render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/rendering.rb:104:in `_render_template'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/streaming.rb:217:in `_render_template'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/rendering.rb:83:in `render_to_body'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/abstract_controller/rendering.rb:26:in `render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/rendering.rb:36:in `render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:43:in `render'
  /root/greenlight/app/controllers/errors_controller.rb:29:in `internal_error'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/abstract_controller/base.rb:188:in `process_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:126:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:455:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/rescue.rb:20:in `process_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:164:in `block in instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:164:in `instrument'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/abstract_controller/base.rb:126:in `process'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionview-5.0.7/lib/action_view/rendering.rb:30:in `process'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal.rb:190:in `dispatch'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_controller/metal.rb:262:in `dispatch'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/routing/route_set.rb:32:in `serve'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/journey/router.rb:39:in `block in serve'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/journey/router.rb:26:in `each'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/journey/router.rb:26:in `serve'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/routing/route_set.rb:727:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/middleware/show_exceptions.rb:49:in `render_exception'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/middleware/show_exceptions.rb:34:in `rescue in call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.0.7/lib/rails/rack/logger.rb:36:in `call_app'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.0.7/lib/rails/rack/logger.rb:24:in `block in call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/tagged_logging.rb:26:in `tagged'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/tagged_logging.rb:69:in `tagged'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.0.7/lib/rails/rack/logger.rb:24:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/middleware/request_id.rb:24:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7/lib/action_dispatch/middleware/static.rb:136:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.0.7/lib/rails/engine.rb:522:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/urlmap.rb:68:in `block in call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `each'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
  /root/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

**Comment by Ciangi** [comment]
I chose the option with installing ruby on rails in BBB server and then tried to run it ...

**Comment by jiama843** [comment]
It looks like you're missing some entries in your database, try running the following from your `./greenlight` directory:

rake db:migrate

**Comment by Ciangi** [comment]
i dont know why but after delete greenlight directory and clone it again it works but still have one problem.
I have "env" configuration file inside greenlight directory. I configured to use LDAP.
when i type:
```
rake server --port=3000
```
I can see webpage but can't log in as LDAP account. I think that this env file is not loaded. how can i load it or smth ?

**Comment by jiama843** [comment]
Since your running it as a rails application, as long as the environment file is named ".env", it has the right configuration and it is located directly under the `./greenlight` directory, your server should pick up the changes.

Can you just double check that those conditions are met?

**Comment by Ciangi** [comment]
oh okay. after changed from "env" to ".env" working but only in development mode.
When i try to run as:
```
rails server --port=3001 --environment=production
```
got this:

![image](https://user-images.githubusercontent.com/15123509/48025784-a362ff80-e144-11e8-8803-d01e4d99e179.png)
![image](https://user-images.githubusercontent.com/15123509/48025828-bfff3780-e144-11e8-9198-c09f1eb9267e.png)


as you can see on images it only showing something when i type domain name and "/b" but it's strange because in .env file i have:
```
RELATIVE_URL_ROOT=/
```

and another problem is when i go to this sites no logs appears but it's because this is production mode right? : 
```
root@192:~/greenlight# rails server --port=3001 --environment=production
=> Booting Puma
=> Rails 5.0.7 application starting in production on http://0.0.0.0:3001
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3001
Use Ctrl-C to stop
```
P.S

in development mode when i type just domain name without "/b" everything works perfect.

**Comment by jiama843** [comment]
Production uses a different database, you have everything configured correctly so far.

To fully run production, you need to run the following:

```
RAILS_ENV=production rake db:setup
RAILS_ENV=production rake db:migrate
RAILS_ENV=production rake assets:precompile
```

Then you can start the server and access the endpoint and everything should look right (yeah for production, if you don't specify RELATIVE_URL_ROOT, you need to add "/b" to the end of your url).

**Comment by Ciangi** [comment]
hmm after this commands still the same problem ….
 I mean now i can see normal web page but can't login with ldap authorization…

 anyway it works in development mode so i'm satisfied.

**Comment by jiama843** [comment]
Oh, I forgot to mention that there is a gem that is used to read from the environment called "dotenv-rails". If you go to the Gemfile, you will see that it is under a group (development, test).

If you bring the gem outside the scope of the group, then ldap should work on production.

**Comment by Ciangi** [comment]
so i just have to do this:
```
group :production, :development, :test do
```
inside Gemfile 
and then just run? :
```
rails server --port=3001 --environment=production
```

**Comment by Ciangi** [comment]
yyy now i have:

```
root@192:~/greenlight# bin/rails server --port=3001 -e production
=> Booting Puma
=> Rails 5.0.7 application starting in production on http://0.0.0.0:3001
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3001
Use Ctrl-C to stop
I, [2018-11-05T23:48:55.054891 #757]  INFO -- omniauth: (ldap) Request phase initiated.
I, [2018-11-05T23:48:55.207365 #757]  INFO -- omniauth: (ldap) Request phase initiated.
```
so ldap auth login page appears but when try to login, wait like 15 secs and then got page:
![image](https://user-images.githubusercontent.com/15123509/48034177-9b17be00-e15e-11e8-9d84-36dd9d6dbf86.png)

**Comment by jiama843** [comment]
That might be because it can't find the callback url. You may need to adjust the ldap settings in your `.env` file to account for the `RELATIVE_URL_ROOT` for production.

**Comment by Ciangi** [comment]
oh, okay. it's true. so 
RELATIVE_URL_ROOT=/     
works only in development mode.
in production i have to add something like
RELATIVE_URL_ROOT=/b
and now it works. 

Thank you very much for help.
