### ISSUE TITLE
Unable to delete room in the dashboard 

### ISSUE THREAD

**Issue by rajbosco** [bigbluebutton/greenlight#3234]
Hi @All 

   I am having a problem of deleting the room. I am getting the following error 

**500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.**

**Comment by hadicheaito1** [comment]
Could you please provide more information such as the logs from ~/greenlight/log/production.log

**Comment by rajbosco** [comment]
`Started DELETE "/" for ::1 at 2022-03-09 10:40:24 +0530
  
ActionController::RoutingError (No route matches [DELETE] "/"):
  
actionpack (5.2.4.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.5) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.4.5) lib/rails/engine.rb:524:in `call'
rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Processing by ErrorsController#not_found as HTML
  Parameters: {"authenticity_token"=>"xyhljG737zwuC8Ew6BwbsXl6QBuDtcC7JEN6Ka6dxCPnxtgEPbU5VoYxirM5P76KMaO0HmH9WwuiU4EIbUSq4w=="}
  [1m[36mSetting Load (0.7ms)[0m  [1m[34mSELECT  "settings".* FROM "settings" WHERE "settings"."provider" = $1 LIMIT $2[0m  [["provider", "cagliero-live"], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:99
  [1m[36mFeature Load (0.3ms)[0m  [1m[34mSELECT "features".* FROM "features" WHERE "features"."setting_id" = $1[0m  [["setting_id", 1]]
  ↳ app/controllers/application_controller.rb:99
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."deleted" = $1 AND "users"."id" = $2 LIMIT $3[0m  [["deleted", false], ["id", 125], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:32
  [1m[36mRole Load (0.3ms)[0m  [1m[34mSELECT "roles".* FROM "roles" WHERE "roles"."id" = $1[0m  [["id", 1]]
  ↳ app/controllers/application_controller.rb:32
  [1m[36mRolePermission Load (0.2ms)[0m  [1m[34mSELECT "role_permissions".* FROM "role_permissions" WHERE "role_permissions"."role_id" = $1[0m  [["role_id", 1]]
  ↳ app/controllers/application_controller.rb:32
  [1m[36mRoom Load (0.4ms)[0m  [1m[34mSELECT "rooms".* FROM "rooms" WHERE "rooms"."deleted" = $1 AND "rooms"."id" = $2[0m  [["deleted", false], ["id", 206]]
  ↳ app/controllers/application_controller.rb:32
  Rendering errors/greenlight_error.html.erb within layouts/application
  Rendered errors/greenlight_error.html.erb within layouts/application (2.3ms)
  Rendered shared/_header.html.erb (4.6ms)
  Rendered shared/components/_cookie_warning.html.erb (0.4ms)
  Rendered shared/_footer.html.erb (1.5ms)
Completed 404 Not Found in 157ms (Views: 140.1ms | ActiveRecord: 2.2ms)


Started GET "/themes/primary.css" for ::1 at 2022-03-09 10:40:25 +0530
Processing by ThemesController#index as CSS
  [1m[36mSetting Load (0.2ms)[0m  [1m[34mSELECT  "settings".* FROM "settings" WHERE "settings"."provider" = $1 LIMIT $2[0m  [["provider", "cagliero-live"], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:99
  [1m[36mFeature Load (0.2ms)[0m  [1m[34mSELECT "features".* FROM "features" WHERE "features"."setting_id" = $1[0m  [["setting_id", 1]]
  ↳ app/controllers/application_controller.rb:99
  Rendering text template
  Rendered text template (0.0ms)
Completed 200 OK in 8ms (Views: 0.3ms | ActiveRecord: 0.4ms)
`

**Comment by rajbosco** [comment]
Started DELETE "/" for ::1 at 2022-03-09 10:40:24 +0530
ActionController::RoutingError (No route matches [DELETE] "/"):
actionpack (5.2.4.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in
`call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in
`call'
railties (5.2.4.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.5) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.5) lib/active_support/tagged_logging.rb:71:in `block
in tagged'
activesupport (5.2.4.5) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.5) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.5) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/remote_ip.rb:81:in
`call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/request_id.rb:27:in
`call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.5)
lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.5) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.4.5) lib/rails/engine.rb:524:in `call'
rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Processing by ErrorsController#not_found as HTML
Parameters: {"authenticity_token"=>
"xyhljG737zwuC8Ew6BwbsXl6QBuDtcC7JEN6Ka6dxCPnxtgEPbU5VoYxirM5P76KMaO0HmH9WwuiU4EIbUSq4w=="
}
[1m [36mSetting Load (0.7ms) [0m [1m [34mSELECT "settings".* FROM "settings"
WHERE "settings"."provider" = $1 LIMIT $2 [0m [["provider", "cagliero-live"],
["LIMIT", 1]]
↳ app/controllers/application_controller.rb:99
[1m [36mFeature Load (0.3ms) [0m [1m [34mSELECT "features".* FROM "features"
WHERE "features"."setting_id" = $1 [0m [["setting_id", 1]]
↳ app/controllers/application_controller.rb:99
[1m [36mUser Load (0.3ms) [0m [1m [34mSELECT "users".* FROM "users" WHERE
"users"."deleted" = $1 AND "users"."id" = $2 LIMIT $3 [0m [["deleted", false],
["id", 125], ["LIMIT", 1]]
↳ app/controllers/application_controller.rb:32
[1m [36mRole Load (0.3ms) [0m [1m [34mSELECT "roles".* FROM "roles" WHERE
"roles"."id" = $1 [0m [["id", 1]]
↳ app/controllers/application_controller.rb:32
[1m [36mRolePermission Load (0.2ms) [0m [1m [34mSELECT "role_permissions".*
FROM "role_permissions" WHERE "role_permissions"."role_id" = $1 [0m [[
"role_id", 1]]
↳ app/controllers/application_controller.rb:32
[1m [36mRoom Load (0.4ms) [0m [1m [34mSELECT "rooms".* FROM "rooms" WHERE
"rooms"."deleted" = $1 AND "rooms"."id" = $2 [0m [["deleted", false], ["id",
206]]
↳ app/controllers/application_controller.rb:32
Rendering errors/greenlight_error.html.erb within layouts/application
Rendered errors/greenlight_error.html.erb within layouts/application (2.3ms)
Rendered shared/_header.html.erb (4.6ms)
Rendered shared/components/_cookie_warning.html.erb (0.4ms)
Rendered shared/_footer.html.erb (1.5ms)
Completed 404 Not Found in 157ms (Views: 140.1ms | ActiveRecord: 2.2ms)


Started GET "/themes/primary.css" for ::1 at 2022-03-09 10:40:25 +0530
Processing by ThemesController#index as CSS
[1m [36mSetting Load (0.2ms) [0m [1m [34mSELECT "settings".* FROM "settings"
WHERE "settings"."provider" = $1 LIMIT $2 [0m [["provider", "cagliero-live"],
["LIMIT", 1]]
↳ app/controllers/application_controller.rb:99
[1m [36mFeature Load (0.2ms) [0m [1m [34mSELECT "features".* FROM "features"
WHERE "features"."setting_id" = $1 [0m [["setting_id", 1]]
↳ app/controllers/application_controller.rb:99
Rendering text template
Rendered text template (0.0ms)
Completed 200 OK in 8ms (Views: 0.3ms | ActiveRecord: 0.4ms)

**Comment by farhatahmad** [comment]
How are you running Greenlight?

**Comment by rajbosco** [comment]
I have used to run in local starting like rails s -p 3000

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
