### ISSUE TITLE
V3: Incomplete schema creation on first startup?

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4163]
**Describe the bug**
After I started a Greenlight 3 instance with a fresh PostgreSQL database, on the first request this happens:
```
=> Booting Puma
=> Rails 7.0.3 application starting in production
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.4 (ruby 3.1.2-p20) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 122
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
I, [2022-11-21T16:35:53.827236 #122]  INFO -- : [2d894114-87de-4ff9-8414-b97bb0d3f2bd] Started GET "/gl3/" for 168.119.44.223 at 2022-11-21 16:35:53 +0100
I, [2022-11-21T16:35:53.828701 #122]  INFO -- : [2d894114-87de-4ff9-8414-b97bb0d3f2bd] Processing by ComponentsController#index as HTML
I, [2022-11-21T16:35:53.828732 #122]  INFO -- : [2d894114-87de-4ff9-8414-b97bb0d3f2bd]   Parameters: {"path"=>"gl3"}
I, [2022-11-21T16:35:53.830796 #122]  INFO -- : [2d894114-87de-4ff9-8414-b97bb0d3f2bd]   Rendered components/index.html.erb within layouts/application (Duration: 0.2ms | Allocations: 175)
I, [2022-11-21T16:35:53.834351 #122]  INFO -- : [2d894114-87de-4ff9-8414-b97bb0d3f2bd]   Rendered layout layouts/application.html.erb (Duration: 3.8ms | Allocations: 1228)
I, [2022-11-21T16:35:53.834530 #122]  INFO -- : [2d894114-87de-4ff9-8414-b97bb0d3f2bd] Completed 200 OK in 6ms (Views: 4.8ms | Allocations: 2558)


I, [2022-11-21T16:36:40.977335 #122]  INFO -- : [0fe540ed-3453-4dbf-9941-120fba2db868] Started GET "/" for 93.215.17.161 at 2022-11-21 16:36:40 +0100
I, [2022-11-21T16:36:40.977978 #122]  INFO -- : [0fe540ed-3453-4dbf-9941-120fba2db868] Processing by ComponentsController#index as HTML
I, [2022-11-21T16:36:40.978388 #122]  INFO -- : [0fe540ed-3453-4dbf-9941-120fba2db868]   Rendered components/index.html.erb within layouts/application (Duration: 0.0ms | Allocations: 4)
I, [2022-11-21T16:36:40.979072 #122]  INFO -- : [0fe540ed-3453-4dbf-9941-120fba2db868]   Rendered layout layouts/application.html.erb (Duration: 0.7ms | Allocations: 620)
I, [2022-11-21T16:36:40.979194 #122]  INFO -- : [0fe540ed-3453-4dbf-9941-120fba2db868] Completed 200 OK in 1ms (Views: 1.0ms | Allocations: 838)
I, [2022-11-21T16:36:41.338908 #122]  INFO -- : [cb35f2c8-da78-4208-a345-6d1a8f11ad7b] Started GET "/api/v1/sessions.json" for 93.215.17.161 at 2022-11-21 16:36:41 +0100
I, [2022-11-21T16:36:41.340262 #122]  INFO -- : [cb35f2c8-da78-4208-a345-6d1a8f11ad7b] Processing by Api::V1::SessionsController#index as JSON
E, [2022-11-21T16:36:41.360816 #122] ERROR -- : [cb35f2c8-da78-4208-a345-6d1a8f11ad7b] PG::UndefinedColumn: ERROR:  column users.session_token does not exist
LINE 1: SELECT "users".* FROM "users" WHERE "users"."session_token" ...
                                            ^

E, [2022-11-21T16:36:41.360946 #122] ERROR -- : [cb35f2c8-da78-4208-a345-6d1a8f11ad7b] /usr/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:837:in `prepare'
/usr/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:837:in `block in prepare_statement'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:832:in `prepare_statement'
/usr/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:778:in `exec_cache'
/usr/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:747:in `execute_and_clear'
/usr/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
/usr/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
/usr/lib/ruby/gems/3.1.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
[...]
```

**To Reproduce**
1. Minimal `docker-compose.yml` setup with PostgreSQL and Greenlight3
2. Wait until start up is complete
3. Access Greenlight 3.

I *did not use* the `greenlight-run` repository with the modified `bin/start`.

**Comment by debuglevel** [comment]
bin/start seems to miss `rake db:schema:load`

**Comment by farhatahmad** [comment]
Hmm this is odd - https://github.com/bigbluebutton/greenlight/blob/v3/bin/start#L17-L18 `bin/start` does a `db:create` followed by a `db:migrate:with_data` which should've create the required tables for you
