### ISSUE TITLE
V3: BrandingImage not found

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4164]
**Describe the bug**
```
greenlight_1  | I, [2022-11-21T17:25:17.048287 #125]  INFO -- : [696afb8a-71f7-46f4-bf21-f7c8cd523a4f] Started GET "/api/v1/site_settings/BrandingImage.json" for 93.215.17.161 at 2022-11-21 17:25:17 +0100
greenlight_1  | I, [2022-11-21T17:25:17.048793 #125]  INFO -- : [696afb8a-71f7-46f4-bf21-f7c8cd523a4f] Processing by Api::V1::SiteSettingsController#show as JSON
greenlight_1  | I, [2022-11-21T17:25:17.048828 #125]  INFO -- : [696afb8a-71f7-46f4-bf21-f7c8cd523a4f]   Parameters: {"name"=>"BrandingImage"}
greenlight_1  | E, [2022-11-21T17:25:17.050717 #125] ERROR -- : [696afb8a-71f7-46f4-bf21-f7c8cd523a4f] undefined method `image' for nil:NilClass
greenlight_1  |
greenlight_1  |     value = if @setting_name == 'BrandingImage' && setting.image.attached?
greenlight_1  |                                                           ^^^^^^
greenlight_1  | E, [2022-11-21T17:25:17.050866 #125] ERROR -- : [696afb8a-71f7-46f4-bf21-f7c8cd523a4f] /usr/src/app/app/services/setting_getter.rb:18:in `call'
greenlight_1  | /usr/src/app/app/controllers/api/v1/site_settings_controller.rb:10:in `show'
greenlight_1  | /usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
greenlight_1  | /usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.3/lib/abstract_controller/base.rb:215:in `process_action'
greenlight_1  | /usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/rendering.rb:53:in `process_action'
greenlight_1  | /usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
greenlight_1  | /usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
greenlight_1  | /usr/lib/ruby/gems/3.1.0/gems/actiontext-7.0.3/lib/action_text/rendering.rb:20:in `with_renderer'
greenlight_1  | /usr/lib/ruby/gems/3.1.0/gems/actiontext-7.0.3/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
greenlight_1  | /usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `instance_exec'
```

**To Reproduce**
1. Fresh startup of Greenlight3 (after injecting the missing `rake db:schema:load`; see https://github.com/bigbluebutton/greenlight/issues/4163)
2. Access Greenlight 3 start page

**Comment by debuglevel** [comment]
```
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

The asset "bbb_logo.png" is not present in the asset pipeline.
/usr/src/app/db/data/20220713143528_populate_site_settings.rb:10:in `up'

Caused by:
Sprockets::Rails::Helper::AssetNotFound: The asset "bbb_logo.png" is not present in the asset pipeline.
/usr/src/app/db/data/20220713143528_populate_site_settings.rb:10:in `up'
Tasks: TOP => db:migrate:with_data
(See full trace by running task with --trace)
== Data =======================================================================
```

**Comment by farhatahmad** [comment]
I can replicate this locally - working on a fix

**Comment by farhatahmad** [comment]
Actually maybe not - was a configuration issue on my side causing the error. 

> The asset "bbb_logo.png" is not present in the asset pipeline.

This is definitely the cause though I'm not quite sure exactly what the cause is. Can you try running `rails assets:precompile` before running `rails data:migrate`? 

It might be easiest for you to to drop your db and restart. If you do try the commands in this order:
```
rails assets:precompile
rails db:create
rails db:migrate:with_data
```

**Comment by debuglevel** [comment]
Great! Putting `assets:precompile` before `data:migrate` in `bin/start` fixes the issue.
