### ISSUE TITLE
Unable to migrate from v2 to v3

### ISSUE THREAD

**Issue by more-zamani** [bigbluebutton/greenlight#5109]
Hi
I've an issue in migration to latest version. It's installed without any problem, but it's empty, and I want to access my previous version data on it.

Both of v2 and v3 is running:
```
docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS          PORTS                      NAMES
c93b747a3e41   bigbluebutton/greenlight:v3           "bin/start"              8 minutes ago    Up 8 minutes    127.0.0.1:5050->3000/tcp   greenlight-v3
441cd28c59ec   postgres:14.6-alpine3.17              "docker-entrypoint.s…"   8 minutes ago    Up 8 minutes    5432/tcp                   postgres
1642b8471ec0   redis:6.2-alpine3.17                  "docker-entrypoint.s…"   8 minutes ago    Up 8 minutes    6379/tcp                   redis
8e2f6cea89f9   bigbluebutton/greenlight:release-v2   "bin/start"              49 minutes ago   Up 49 minutes   127.0.0.1:5000->80/tcp     greenlight-v2
afdb574924dc   postgres:13-alpine                    "docker-entrypoint.s…"   49 minutes ago   Up 49 minutes   127.0.0.1:5432->5432/tcp   greenlight_db_1
```

After [these steps](https://docs.bigbluebutton.org/greenlight/v3/migration#the-rake-migration-task-file), I execute this command:
`sudo docker exec -it greenlight-v2 bundle exec rake migrations:roles`
and get these errors:

```
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: already initialized constant Net::ProtocRetryError
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: previous definition of Socket was here
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.7.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Unable to migrate Role:
ID: 34
Name: استاد
rake aborted!
JSON::ParserError: 859: unexpected token at '<!--BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.-->

<!--Copyright (c) 2022 BigBlueButton Inc. and by respective authors (see below).-->

<!--This program is free software; you can redistribute it and/or modify it under the-->
<!--terms of the GNU Lesser General Public License as published by the Free Software-->
<!--Foundation; either version 3.0 of the License, or (at your option) any later-->
<!--version.-->

<!--Greenlight is distributed in the hope that it will be useful, but WITHOUT ANY-->
<!--WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A-->
<!--PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.-->

<!--You should have received a copy of the GNU Lesser General Public License along-->
<!--with Greenlight; if not, see <http://www.gnu.org/licenses/>.-->


<!DOCTYPE html>
<html>
  <head>
    <title>BigBlueButton</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- Open Graph Attributes -->
    <meta property="og:title" content="BigBlueButton" />
    <meta property="og:description" content="" />
    <meta property="og:image" content="https://xxxxxx.xxxxxx/assets/bbb_logo-176f5d8146a2dc0605ec62f28bdaf3c2addce6747143ca19de1f8e85134f020f.png" />


    <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="gICaW3vLUS78EImNyXzjtBC-_H2ZMqeDyVU1XX4DyKNFjw6Khva3C6X6H4c-p8s8Lg5xL_McVtZedoAzKjvdHQ" />


    <link rel="stylesheet" href="/assets/application-afb0d51436cd4fbc81878f0390461a59c7db44056ff6718403061734dc031b2b.css" />
    <script src="/assets/main-005a23eb8402f04d86b28ddc7a51dcdc3eb937e2022984e1678f6456f94a0eaf.js" defer="defer"></script>
  </head>

  <body>
    <!--BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.-->

<!--Copyright (c) 2022 BigBlueButton Inc. and by respective authors (see below).-->

<!--This program is free software; you can redistribute it and/or modify it under the-->
<!--terms of the GNU Lesser General Public License as published by the Free Software-->
<!--Foundation; either version 3.0 of the License, or (at your option) any later-->
<!--version.-->

<!--Greenlight is distributed in the hope that it will be useful, but WITHOUT ANY-->
<!--WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A-->
<!--PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.-->

<!--You should have received a copy of the GNU Lesser General Public License along-->
<!--with Greenlight; if not, see <http://www.gnu.org/licenses/>.-->


<div id="root"></div>

  </body>
</html>

'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
/usr/src/app/lib/tasks/migrations/migrations.rake:50:in `block (3 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `block in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:222:in `loop'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:69:in `find_each'
/usr/src/app/lib/tasks/migrations/migrations.rake:21:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => migrations:roles
(See full trace by running task with --trace)
```

**Comment by scouillard** [comment]
Hi,
1. Would you confirm you are pointing to the right V3 endpoint? `V3_ENDPOINT` in your `.env` file.
2. Would you confirm you are using the latest GLv3 image? Please run the following command:
`docker exec -it greenlight-v3 printenv | grep VERSION`

**Comment by TomSemilia** [comment]
Hey,
I have configured this as my endpoint:
```
V3_ENDPOINT=https://bbb-test.oth-aw.de/
```

I get this output:
```
root@bbb-test:~# root@bbb26:~/greenlight-v3# docker exec -it greenlight-v3 printenv | grep VERSION
-bash: root@bbb26:~/greenlight-v3#: No such file or directory
root@bbb-test:~# VERSION_TAG=release-3.0.3.1
```
