### ISSUE TITLE
[3.0] Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/greenlight#5110]
Ubuntu 22.04, nginx 1.22, scalelite
very strange error when trying to start meeting or list server's rooms.

official docker images Greenlight 3.0.1, 3.0.2 master on current date.
manage to figure out the real error with **master** image

nginx errors.log:
2023/04/02 17:48:51 [error] 140701#140701: *36 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 111.11.39.6, server: domain.com, request: "GET /rooms HTTP/2.0", upstream: "http://127.0.0.1:5050/rooms", host: "domain.com"

greenlight log
> I, [2023-04-02T17:51:50.368102 #136]  INFO -- : [b05f8dd3-cfd2-4038-82c8-5f1ee55bdcbc] Started POST "/api/v1/meetings/ijd-x0o-fmp-txw/start.json" for 195.64.239.46 at 2023-04-02 17:51:50 +0000
> I, [2023-04-02T17:51:50.371066 #136]  INFO -- : [b05f8dd3-cfd2-4038-82c8-5f1ee55bdcbc] Processing by Api::V1::MeetingsController#start as JSON
> I, [2023-04-02T17:51:50.371201 #136]  INFO -- : [b05f8dd3-cfd2-4038-82c8-5f1ee55bdcbc]   Parameters: {"friendly_id"=>"ijd-x0o-fmp-txw"}
> I, [2023-04-02T17:51:50.507394 #136]  INFO -- : [b05f8dd3-cfd2-4038-82c8-5f1ee55bdcbc] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.23ms)
> I, [2023-04-02T17:51:50.508432 #136]  INFO -- : [b05f8dd3-cfd2-4038-82c8-5f1ee55bdcbc] Completed 400 Bad Request in 137ms (Views: 3.9ms | ActiveRecord: 58.3ms | Allocations: 10717)
> I, [2023-04-02T17:51:51.614619 #136]  INFO -- : [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] Started POST "/remote/logincheck" for 91.215.85.10 at 2023-04-02 17:51:51 +0000
> I, [2023-04-02T17:51:51.616811 #136]  INFO -- : [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] Processing by ComponentsController#index as */*
> I, [2023-04-02T17:51:51.617001 #136]  INFO -- : [1ebc2539-81c4-4f5e-8455-e18ffdc6139b]   Parameters: {"ajax"=>"1", "username"=>"user", "credential"=>"!QAZ2wsx", "path"=>"remote/logincheck"}
> W, [2023-04-02T17:51:51.617480 #136]  WARN -- : [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] Can't verify CSRF token authenticity.
> I, [2023-04-02T17:51:51.619063 #136]  INFO -- : [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] Completed 422 Unprocessable Entity in 2ms (ActiveRecord: 0.0ms | Allocations: 181)
> F, [2023-04-02T17:51:51.622566 #136] FATAL -- : [1ebc2539-81c4-4f5e-8455-e18ffdc6139b]   
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] ActionController::InvalidAuthenticityToken (Can't verify CSRF token authenticity.):
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b]   
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_controller/metal/request_forgery_protection.rb:251:in `handle_unverified_request'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_controller/metal/request_forgery_protection.rb:284:in `handle_unverified_request'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_controller/metal/request_forgery_protection.rb:273:in `verify_authenticity_token'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/callbacks.rb:400:in `block in make_lambda'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/callbacks.rb:200:in `block in halting'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/callbacks.rb:595:in `block in invoke_before'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/callbacks.rb:595:in `each'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/callbacks.rb:595:in `invoke_before'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/callbacks.rb:138:in `run_callbacks'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activerecord (7.0.4.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/abstract_controller/base.rb:151:in `process'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionview (7.0.4.3) lib/action_view/rendering.rb:39:in `process'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_controller/metal.rb:188:in `dispatch'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_controller/metal.rb:251:in `dispatch'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/routing/mapper.rb:48:in `serve'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `each'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `serve'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] omniauth (2.1.1) lib/omniauth/builder.rb:44:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/tempfile_reaper.rb:15:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/etag.rb:27:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/conditional_get.rb:40:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/head.rb:12:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/session/abstract/id.rb:266:in `context'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/session/abstract/id.rb:260:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/cookies.rb:704:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] railties (7.0.4.3) lib/rails/rack/logger.rb:40:in `call_app'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] railties (7.0.4.3) lib/rails/rack/logger.rb:25:in `block in call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:99:in `block in tagged'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:37:in `tagged'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:99:in `tagged'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] railties (7.0.4.3) lib/rails/rack/logger.rb:25:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/method_override.rb:24:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/runtime.rb:22:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] activesupport (7.0.4.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/static.rb:23:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/sendfile.rb:110:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] actionpack (7.0.4.3) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] railties (7.0.4.3) lib/rails/engine.rb:530:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/urlmap.rb:74:in `block in call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/urlmap.rb:58:in `each'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] rack (2.2.6.4) lib/rack/urlmap.rb:58:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] puma (5.6.5) lib/puma/configuration.rb:252:in `call'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] puma (5.6.5) lib/puma/server.rb:443:in `process_client'
> [1ebc2539-81c4-4f5e-8455-e18ffdc6139b] puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
>

**Comment by amg-web** [comment]
fixed by adding to /etc/hosts
ip hostname

eg:
111.111.111.111 myhostname.com
