### ISSUE TITLE
Can't migrate from greenlight 2 to 3

### ISSUE THREAD

**Issue by Oblation** [bigbluebutton/greenlight#5153]
Hello,

I have a problem with the migration from greenlight 2 to 3.

Background: bbb 2.4 (previously from bbb 2.3) with greenlight-v2 reinstalled in the latest version 2.5 with migration of records and dump of greenlight database on an Ubuntu 20.04.6 LTS , external turn server. Then updated to version 2.6 with greenlight-v3 installed on the same server.

Both greenlight version are present and running : 

```
####@####:~/greenlight# docker exec -it greenlight-v2 printenv | grep VERSION
RUBY_VERSION=2.7.7
VERSION_CODE=release-2.14.6
```
```
####@####:~/greenlight# docker exec -it greenlight-v3 printenv | grep VERSION
VERSION_TAG=release-3.0.3.1
```

`V3_ENDPOINT` in the `.env` file pointing on the right v3 endpoint (like https://example.com/gl/)

Like [this issue](https://github.com/bigbluebutton/greenlight/issues/5109)  I get an error when passing the command

`sudo docker exec -it greenlight-v2 bundle exec rake migrations:roles`

Command return with the --trace option:

```
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: already initialized constant Net::ProtocRetryError
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: previous definition of Socket was here
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.7.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
rake aborted!
Don't know how to build task 'migrations:roles' (See the list of available tasks with `rake --tasks`)
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task_manager.rb:59:in `[]'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:159:in `invoke_task'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'
/usr/src/app/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/usr/local/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

**Comment by goekce** [comment]
I had also many difficulties after running `bbb-install-2.6.sh` script on BBB 2.5. I do not know if this is also your case. My recommendation:

1. Do not forget to restart after running `bbb-install-2.6.sh`. Otherwise `haproxy` may not be started. (probably the install script does not use `systemctl enable --now ...`)
2. If you use `haproxy` make sure `/etc/nginx/sites-enabled/bigbluebutton` is not using 443. 443 belongs to `haproxy`. Otherwise you may have to fix the nginx config manually according to the content of `bbb-install-2.6.sh`. Then I would rerun  `bbb-install-2.6.sh`, because some components of the script may not have completed.
3. If above do not help, you could give more info about your installation process.

After correct installation greenlight-v2 should be available at `example.com/b` and greenlight-v3 at `example.com`.

**Comment by scouillard** [comment]
Hi,
Are you sure you are using Greenlight v2 latest version?
From the error log, I suspect it is not up to the latest version.
Thank you.

**Comment by goekce** [comment]
Glad to hear that you solved your problem @Oblation . If you went for a clear installation, then there is nothing to debug I guess. Do not forget to close this issue then.

**Comment by Oblation** [comment]
Hello,

I closed this issue, problem "fixed" through an installation from scratch
