### ISSUE TITLE
V2/3: Show some information about why migration fails

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#5257]
```
# docker exec -it greenlight2_greenlight bundle exec rake migrations:roles --verbose --trace
[... skipped warnings ...]
** Invoke migrations:roles (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute migrations:roles
Unable to migrate Role:
ID: 6
Name: Freischalter
Provider: greenlight
rake aborted!
JSON::ParserError: 859: unexpected token at '<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
[...]
```

This does not output much information what the migration job just tried to access. It would be nice if there was some output like

```
GET http://host.org/gl3/roles
[...]

POST http://host.org/gl3/rooms/1138
[...]
````

Maybe even the JSON sent (e.g. if `--trace` is active), the HTTP status et cetera.

**Comment by psy** [comment]
any news / progress here?

**Comment by ffdixon** [comment]
We recommend trying the migration with the latest version of GreenLight and let us know if you encounter any issues.

**Comment by psy** [comment]
I did and all I got was "InvalidParameter". Not really helpful.

**Comment by kidhab** [comment]
> JSON::ParserError: 859: unexpected token at '<html>
> <head><title>404 Not Found</title></head>

The same error occurs if your `V3_ENDPOINT` variable doesn't have a tailing slash. Maybe that's also the case with your setup?

The [documentation](https://docs.bigbluebutton.org/greenlight/v3/migration/) shows this only in the example.
