### ISSUE TITLE
V2/3: `migrations:settings` fails on V3 endpoint

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#5259]
```
# docker exec -it greenlight2_greenlight bundle exec rake migrations:settings --verbose --trace
[ ... skip warnings ... ]
** Invoke migrations:settings (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute migrations:settings
Unable to migrate Settings
Provider: greenlight
Errors: ["SomethingWentWrong"]

Settings migration completed.
In case of an error please retry the process to resolve.
```

Would be nice to get _some_ information about what went wrong.

**Comment by debuglevel** [comment]
The Greenlight 3 endpoint told me this:

```
I, [2023-06-20T14:09:53.082871 #156]  INFO -- : [488db818-d0fb-47f6-b854-aa97247d6441] Started POST "/gl3/api/v1/migrations/settings.json" for 172.18.0.3 at 2023-06-20 14:09:53 +0200
I, [2023-06-20T14:09:53.083698 #156]  INFO -- : [488db818-d0fb-47f6-b854-aa97247d6441] Processing by Api::V1::Migrations::ExternalController#create_settings as JSON
I, [2023-06-20T14:09:53.083742 #156]  INFO -- : [488db818-d0fb-47f6-b854-aa97247d6441]   Parameters: {"v2"=>{"encrypted_params"=>"[FILTERED]"}, "external"=>{"v2"=>{"encrypted_params"=>"[FILTERED]"}}}
E, [2023-06-20T14:09:53.094597 #156] ERROR -- : [488db818-d0fb-47f6-b854-aa97247d6441] undefined method `keys' for nil:NilClass

                                                         .where('meeting_options.name': settings_hash[:room_configurations].keys,
                                                                                                                           ^^^^^
E, [2023-06-20T14:09:53.094794 #156] ERROR -- : [488db818-d0fb-47f6-b854-aa97247d6441] /usr/src/app/app/controllers/api/v1/migrations/external_controller.rb:178:in `create_settings'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/abstract_controller/base.rb:215:in `process_action'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal/rendering.rb:53:in `process_action'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/lib/ruby/gems/3.1.0/gems/actiontext-7.0.4.3/lib/action_text/rendering.rb:20:in `with_renderer'
/usr/lib/ruby/gems/3.1.0/gems/actiontext-7.0.4.3/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/abstract_controller/callbacks.rb:233:in `process_action'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `instrument'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
/usr/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/abstract_controller/base.rb:151:in `process'
/usr/lib/ruby/gems/3.1.0/gems/actionview-7.0.4.3/lib/action_view/rendering.rb:39:in `process'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal.rb:188:in `dispatch'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal.rb:251:in `dispatch'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `each'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
/usr/lib/ruby/gems/3.1.0/gems/omniauth-2.1.1/lib/omniauth/builder.rb:44:in `call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/etag.rb:27:in `call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/conditional_get.rb:40:in `call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/head.rb:12:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:266:in `context'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:260:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/cookies.rb:704:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:99:in `run_callbacks'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
/usr/lib/ruby/gems/3.1.0/gems/railties-7.0.4.3/lib/rails/rack/logger.rb:40:in `call_app'
/usr/lib/ruby/gems/3.1.0/gems/railties-7.0.4.3/lib/rails/rack/logger.rb:25:in `block in call'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/lib/ruby/gems/3.1.0/gems/railties-7.0.4.3/lib/rails/rack/logger.rb:25:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/method_override.rb:24:in `call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/runtime.rb:22:in `call'
/usr/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/static.rb:23:in `call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/sendfile.rb:110:in `call'
/usr/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
/usr/lib/ruby/gems/3.1.0/gems/railties-7.0.4.3/lib/rails/engine.rb:530:in `call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/urlmap.rb:74:in `block in call'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/urlmap.rb:58:in `each'
/usr/lib/ruby/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/urlmap.rb:58:in `call'
/usr/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/configuration.rb:252:in `call'
/usr/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/request.rb:77:in `block in handle_request'
/usr/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/usr/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/request.rb:76:in `handle_request'
/usr/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
/usr/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
I, [2023-06-20T14:09:53.095145 #156]  INFO -- : [488db818-d0fb-47f6-b854-aa97247d6441] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.05ms)
I, [2023-06-20T14:09:53.095273 #156]  INFO -- : [488db818-d0fb-47f6-b854-aa97247d6441] Completed 500 Internal Server Error in 11ms (Views: 0.4ms | ActiveRecord: 1.4ms | Allocations: 5200)
```

**Comment by debuglevel** [comment]
Yes. Should be the current v2 and v3 docker images.

**Comment by debuglevel** [comment]
Works with `bigbluebutton/greenlight:v3.0.5-alpha2-alpine`
