### ISSUE TITLE
Migration fails: undefined method `green' 

### ISSUE THREAD

**Issue by samuelpetrosyan** [bigbluebutton/greenlight#5300]
I am running on greenlight v2.11 and new v3.

I do everything regarding of https://docs.bigbluebutton.org/greenlight/v3/migration.

But when I execute sudo `docker exec -it greenlight-v2 bundle exec rake migrations:roles` it brings me Error:
```
rake aborted!
NoMethodError: undefined method `green' for main:Object
/usr/src/app/lib/tasks/migrations/migrations.rake:46:in `block (3 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:70:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:70:in `block in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:222:in `loop'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:69:in `find_each'
/usr/src/app/lib/tasks/migrations/migrations.rake:23:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => migrations:roles
(See full trace by running task with --trace)
```

What should I do to fix it? 
Thanks in advance!

**Comment by farhatahmad** [comment]
Can you try upgrading v2?

**Comment by samuelpetrosyan** [comment]
Yes upgrading v2.4.18 version helped thanks.
