### ISSUE TITLE
Fresh install BBB 2.6 w/ Greenlight - 500 error

### ISSUE THREAD

**Issue by jarrodjay** [bigbluebutton/greenlight#5324]
After a fresh install of BBB 2.6 w/ Greenlight, I'm getting a 500 error.
Installed using: wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s xxx.xxxx.com -e xxxxx@xxxxx.com -w -g

 Looking at the logs from docker, it's filled with lots of these:

`I, [2023-07-11T11:53:20.318742 #36]  INFO -- : [2ca3fa0f-30fa-49e5-a0df-01e516464535] method=GET path=/ format=html controller=ComponentsController action=index status=500 duration=1.78 view=0.00 db=0.57 time=2023-07-11 11:53:20 UTC host=greenlight
F, [2023-07-11T11:53:20.319355 #36] FATAL -- : [2ca3fa0f-30fa-49e5-a0df-01e516464535]
[2ca3fa0f-30fa-49e5-a0df-01e516464535] ActionView::Template::Error (nil is not a valid asset source):
[2ca3fa0f-30fa-49e5-a0df-01e516464535]     22:     
[2ca3fa0f-30fa-49e5-a0df-01e516464535]     23:     <meta property="og:title" content="<%= page_title %>" />
[2ca3fa0f-30fa-49e5-a0df-01e516464535]     24:     <meta property="og:description" content="<%= t('opengraph.description') %>" />
[2ca3fa0f-30fa-49e5-a0df-01e516464535]     25:     <meta property="og:image" content="<%= branding_image %>" />
[2ca3fa0f-30fa-49e5-a0df-01e516464535]     26:
[2ca3fa0f-30fa-49e5-a0df-01e516464535]     27:     <%= csrf_meta_tags %>
[2ca3fa0f-30fa-49e5-a0df-01e516464535]     28:     <%= csp_meta_tag %>
[2ca3fa0f-30fa-49e5-a0df-01e516464535]
[2ca3fa0f-30fa-49e5-a0df-01e516464535] app/helpers/application_helper.rb:22:in `branding_image'
[2ca3fa0f-30fa-49e5-a0df-01e516464535] app/views/layouts/application.html.erb:25`

When trying to create an admin user, I get the following: 

`rake aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'verified' for User.
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activemodel-7.0.4.3/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/attribute_assignment.rb:13:in `each'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/attribute_assignment.rb:13:in `_assign_attributes'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activemodel-7.0.4.3/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/core.rb:468:in `initialize'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/inheritance.rb:75:in `new'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/inheritance.rb:75:in `new'
/usr/src/app/lib/tasks/user.rake:33:in `block (2 levels) in <main>'
/usr/src/app/lib/tasks/admin.rake:31:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => user:create
(See full trace by running task with --trace)`

No custom config at all.
Appreciate any help! Thank you.

**Comment by farhatahmad** [comment]
Can you try running `docker exec -it greenlight-v3 bundle exec rails db:migrate:with_data`
