### ISSUE TITLE
smtp oauth2  office365

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/greenlight#5404]
Microsoft deprecated Basic authentication in Exchange Online
https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online

I think I can use legacy endpoint.

but is it possible to add **oauth2** form **smtp** ?
possible gems
https://gitlab.com/oauth-xx/oauth2/
https://github.com/ekohe/ruby-office365

**Comment by amg-web** [comment]
net-smtp supports sending mail with **xoauth2** https://github.com/ruby/net-smtp/releases/tag/v0.5.0
but I failed to succeed with it.
is anything is missing in the code?

> greenlight-v3        | I, [2025-08-26T14:09:39.541670 #1]  INFO -- : [048c67b6-6625-4e53-beb8-e6d1918aff99] method=GET path=/api/v1/admin/invitations.json format=json controller=Api::V1::Admin::InvitationsController action=index status=200 allocations=1883 duration=53.08 view=38.82 db=3.28 time=2025-08-26 14:09:39 UTC host=greenlight
> greenlight-v3        | E, [2025-08-26T14:09:44.435815 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [3d2a8b7c-6063-4e99-aa86-8c6c0f7daf50] Error performing ActionMailer::MailDeliveryJob (Job ID: 3d2a8b7c-6063-4e99-aa86-8c6c0f7daf50) from Async(greenlight_v3_production_mailing) in 5176.59ms: Net::ReadTimeout (Net::ReadTimeout with #<TCPSocket:(closed)>):
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:229:in `rbuf_fill'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:199:in `readuntil'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:209:in `readline'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:1017:in `recv_response'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:992:in `get_response'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-smtp-0.5.0/lib/net/smtp/authenticator.rb:44:in `finish'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-smtp-0.5.0/lib/net/smtp/auth_xoauth2.rb:8:in `auth'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:875:in `authenticate'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:687:in `do_start'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:642:in `start'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/mail-2.8.1/lib/mail/message.rb:2145:in `do_delivery'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `block in deliver'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.2.2.1/lib/action_mailer/base.rb:600:in `block in deliver_mail'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/notifications.rb:212:in `instrument'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.2.2.1/lib/action_mailer/base.rb:598:in `deliver_mail'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `deliver'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.2.2.1/lib/action_mailer/message_delivery.rb:126:in `block (2 levels) in deliver_now'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.2.2.1/lib/action_mailer/message_delivery.rb:125:in `block in deliver_now'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.2.2.1/lib/action_mailer/rescuable.rb:21:in `handle_exceptions'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.2.2.1/lib/action_mailer/message_delivery.rb:124:in `deliver_now'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.2.2.1/lib/action_mailer/mail_delivery_job.rb:28:in `perform'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/execution.rb:68:in `block in _perform_job'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/i18n-1.14.6/lib/i18n.rb:353:in `with_locale'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:130:in `instance_exec'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:130:in `instance_exec'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:141:in `run_callbacks'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/execution.rb:67:in `_perform_job'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/instrumentation.rb:32:in `_perform_job'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/execution.rb:51:in `perform_now'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/instrumentation.rb:26:in `block in perform_now'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/instrumentation.rb:40:in `block in instrument'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/notifications.rb:210:in `block in instrument'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/notifications.rb:210:in `instrument'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/instrumentation.rb:39:in `instrument'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/railties/job_runtime.rb:11:in `instrument'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/instrumentation.rb:26:in `perform_now'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/logging.rb:32:in `block in perform_now'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/tagged_logging.rb:138:in `block in tagged'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/tagged_logging.rb:38:in `tagged'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/tagged_logging.rb:138:in `tagged'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/broadcast_logger.rb:241:in `method_missing'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/logging.rb:39:in `tag_logger'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/logging.rb:32:in `perform_now'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/execution.rb:29:in `block in execute'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/railtie.rb:79:in `block (4 levels) in <class:Railtie>'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/reloader.rb:77:in `block in wrap'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/reloader.rb:74:in `wrap'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/railtie.rb:78:in `block (3 levels) in <class:Railtie>'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:130:in `instance_exec'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:141:in `run_callbacks'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/execution.rb:27:in `execute'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.2.2.1/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
> greenlight-v3        | <internal:kernel>:187:in `loop'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
> greenlight-v3        | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
>
