### ISSUE TITLE
Can't set "default_locale" to my desired language

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/greenlight#5423]
Hi.
I want to set default locale to fa_IR (Farsi) but in `.env` file, none of these values is accepted:
`fa_ir fa_IR fa-IR fa`

I always get such error in docker container logs:

```
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.1/lib/i18n.rb:351:in `enforce_available_locales!': "fa_ir" is not a valid locale (I18n::InvalidLocale)

        raise I18n::InvalidLocale.new(locale) if !locale_available?(locale)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.1/lib/i18n/config.rb:36:in `default_locale='
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.1/lib/i18n.rb:74:in `default_locale='
        from /usr/src/app/config/initializers/locales.rb:22:in `<main>'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:667:in `load'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:667:in `block in load_config_initializer'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/notifications.rb:208:in `instrument'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:666:in `load_config_initializer'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:619:in `each'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:32:in `run'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:50:in `each'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:50:in `tsort_each_child'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `call'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:60:in `run_initializers'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/application.rb:372:in `initialize!'
        from /usr/src/app/config/environment.rb:23:in `<main>'
        from config.ru:5:in `require_relative'
        from config.ru:5:in `block in <main>'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:312:in `block in start'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:379:in `handle_profiling'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:311:in `start'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/commands/server/server_command.rb:38:in `start'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/commands/server/server_command.rb:143:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/commands/server/server_command.rb:134:in `perform'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/command/base.rb:87:in `perform'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/command.rb:48:in `invoke'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/commands.rb:18:in `<main>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/src/app/bin/rails:4:in `<main>'

```

**Comment by ZhmerenkaSolution** [comment]
Same issue with `uk`
