### ISSUE TITLE
Rooms Controller Spec failing in release-3.0.8.1

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/greenlight#5473]
```
Failures:
  1) Api::V1::RoomsController#public_recordings Pagination No page returns :ok with a list of the first page room public recordings
     Failure/Error: expect(response.parsed_body['data'].pluck('id')).to match_array(recordings.pluck('id'))
       expected collection contained:  ["15aa5af5-b03f-4f2c-8513-243c32dbcd0f", "167a0266-bc6c-433d-99c1-eb6d9f098a1c", "3e4004a6-c84f-4b5f-...-9928-78827d38728a", "db50cc4a-6739-4102-9a1e-b31780cdacc6", "f575abde-bbeb-4e12-b326-0208b6bc64ca"]
       actual collection contained:    ["042fbda3-797f-47b2-b13b-966831395046", "069bf478-78b9-4343-b2c7-660b522f1fc1", "15aa5af5-b03f-4f2c-...-b7e9-56e7dfd756ef", "cad5df54-e40d-462e-9928-78827d38728a", "fd77b562-ba9e-4b6e-b25f-a408799f755b"]
       the missing elements were:      ["167a0266-bc6c-433d-99c1-eb6d9f098a1c", "4a5a7838-01e1-4929-afd3-e6901f036ef5", "93fc23c7-2964-48be-...-8243-bea3bdc7666f", "db50cc4a-6739-4102-9a1e-b31780cdacc6", "f575abde-bbeb-4e12-b326-0208b6bc64ca"]
       the extra elements were:        ["042fbda3-797f-47b2-b13b-966831395046", "069bf478-78b9-4343-b2c7-660b522f1fc1", "3a530c2b-af37-408b-...-898d-de6b420cc5c0", "c0374bab-5df2-43ef-b7e9-56e7dfd756ef", "fd77b562-ba9e-4b6e-b25f-a408799f755b"]
     # ./spec/controllers/rooms_controller_spec.rb:373:in `expect_response_to_have'
     # ./spec/controllers/rooms_controller_spec.rb:398:in `block (5 levels) in <main>'
     # /cache/ruby/3.1.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'
```

**Comment by Ithanil** [comment]
Nevermind, I don't get this anymore.
