### ISSUE TITLE
CSRF Error only on particular instance, to be investigated further

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/greenlight#5479]
~~Since [release-3.0.8.1](https://github.com/bigbluebutton/greenlight/releases/tag/release-3.0.8.1)~~ I noticed that I can get a CSRF error and am not able to start rooms / log out etc. in that particular browser tab, when I do the following:

- Not sure if necessary: Use external authn, log in with admin account
- Copy the link of one of your rooms
- Log out in that tab
- open a new tab, paste the link, log in on the join card
- Switch back to the previous tab
- You are now logged in there as well, but can't do anything meaningful ("The action can't be completed. please try again.")

In the server logs I see:

```
2023-10-23T07:12:39.997360+02:00 bbbtest-greenlight3-01 greenlight3_app.2.m7yixiixhdrmg04qycwrz1oy8/11db475fe5aa[852]: I, [2023-10-23T05:12:39.997156 #135]  INFO -- : [d365a28b-7f84-443c-a51e-03edae1f6671] method=GET path=/api/v1/rooms.json format=json controller=Api::V1::RoomsController action=index status=200 allocations=5560 duration=28.53 view=6.00 db=8.55 time=2023-10-23 05:12:39 UTC host=greenlight
2023-10-23T07:12:42.953396+02:00 bbbtest-greenlight3-01 greenlight3_app.2.m7yixiixhdrmg04qycwrz1oy8/11db475fe5aa[852]: W, [2023-10-23T05:12:42.952668 #135]  WARN -- : [e7421f56-0df4-4c02-ac46-ee11812bedc7] Can't verify CSRF token authenticity.
2023-10-23T07:12:42.953620+02:00 bbbtest-greenlight3-01 greenlight3_app.2.m7yixiixhdrmg04qycwrz1oy8/11db475fe5aa[852]: E, [2023-10-23T05:12:42.952929 #135] ERROR -- : [e7421f56-0df4-4c02-ac46-ee11812bedc7] Can't verify CSRF token authenticity.
2023-10-23T07:12:42.953755+02:00 bbbtest-greenlight3-01 greenlight3_app.2.m7yixiixhdrmg04qycwrz1oy8/11db475fe5aa[852]: E, [2023-10-23T05:12:42.953186 #135] ERROR -- : [e7421f56-0df4-4c02-ac46-ee11812bedc7] /usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.0/lib/action_controller/metal/request_forgery_protection.rb:293:in `handle_unverified_request'
2023-10-23T07:12:42.953860+02:00 bbbtest-greenlight3-01 greenlight3_app.2.m7yixiixhdrmg04qycwrz1oy8/11db475fe5aa[852]: /usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.0/lib/action_controller/metal/request_forgery_protection.rb:388:in `handle_unverified_request'
```

I can't reproduce the same ~~with earlier versions, so it must have been introduced with 3.0.8.1.~~ on other instances and so far I have no idea why that is. I'll update the issue as soon as I know more.

**Comment by ffdixon** [comment]
Good catch.

**Comment by Ithanil** [comment]
@ffdixon @farhatahmad Yes, but it is not actually an issue with GL3 but has to do with the configuration of that particular GL instance and our IDP. Sorry... I'll close the issue.
