### ISSUE TITLE
server_recording_sync not working

### ISSUE THREAD

**Issue by lkrbbsb** [bigbluebutton/greenlight#5535]
After migration from v2 to v3, i want to re-sync all the recordings on the new server (all of them are transfered).

But:
```
root@bbb ~ # docker exec -it greenlight-v3 bundle exec rake server_recordings_sync
I, [2023-11-19T16:34:15.167911 #234]  INFO -- : BigBlueButtonAPI: request=https://bbbserver.tld/bigbluebutton/api/getRecordings?meetingID=fwlip5h0dlr61soyosdoccghtrtntpp6s3ftctbe%2Chklj7eh5ijb2bnfvnwtaugwqtxbl0fcirksw0jxg%2C2lftlblzhp2zhom1dzxwoufsnfp2zehisotfcod8%2Cdvzr3gpcqrxdccma8t1tleswtyknuujywee7mnpt%2Clcbgxobztuzoz1visdmy3n1bg8rwm0aiut35lqar%2Chfadmplxrxlotmf8qerdmofdhm34tfw4ybjoqfml%2Czpxd9yrynbrkibuahchbtov6qey6ryaybbabdpg3%2Cmpzy45ez0hlsd0kiodp1v1vwy1vlhpvyhnv1diy1%2Csq0f7x12nys3vu6s4ajyaf6mgkwc871sdqvqxckv%2Chdknzcrcs7yzjfsvsolyl1va5jcjxxnbamma7ytb%2Cdrjatja6xvunvyfgdepli10qp1etrll4ke0bbal7%2C4wzisrjadjbloozd9warhntfgrnzxtdbp824ddxj%2Cn6vun5v2esytderbzo8lwgpulloaafmfrmg8z90b%2Cui43ujheqmu3kh7ul3pgf8ixxn6wjokjmzxvrksr%2Cjfn2llvjmxqed37qp14ocm3is8aiijparyla65au%2Caapdgiwuxilow5bgfxjg7vwl92hoyxgxbxlbmk2s%2Cemhbusmbwpmmvnjg5drnl8x54ooc8id1pfu6rh2q%2C4bonzk2xvfyt7fl6bp5sd3ue5q3nsne1r12agf0e%2Cg0h5up2771b4pyvlpcd2ysegvs7m0cmpmlh2abwc%2C5x3ubnwwdpg1e17nopskh8vhoswredufjbuwsfxj%2C5kba7dzkr4klv6k2z1iv2fcuqtlxjyc4ty4fu0ox%2Cezciecehabymbrm49d5ud6dvhks40ucioweqtqo3%2Cbe9kbgnwialebi88qieymtnwh5gp4kkk4dkncm3o%2Cjfbw9rd2fqrgzm4jdnta4dxbtcmk8y7kt3gdiw6p%2Cjhykaors8nwdty5hkdc0n8m1fxrzmwefkvfkw17s&checksum=6bc4d917d1d6e9ccb577f40004dd2b6a9d7e7130 response_status=Net::HTTPOK response_code=200  message_key=
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/usr/src/app/lib/tasks/server_recordings_sync.rake:30:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.0/lib/active_record/relation/batches.rb:396:in `block in batch_on_unloaded_relation'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.0/lib/active_record/relation/batches.rb:372:in `loop'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.0/lib/active_record/relation/batches.rb:372:in `batch_on_unloaded_relation'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.0/lib/active_record/relation/batches.rb:269:in `in_batches'
/usr/src/app/lib/tasks/server_recordings_sync.rake:24:in `block in <main>'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => server_recordings_sync
(See full trace by running task with --trace)
```

What is wrong there?

When i do this for each room, everything is fine.

**Comment by farhatahmad** [comment]
Looks like a bug in the code if no recordings are returned. I'll have this fixed in the next release

**Comment by lkrbbsb** [comment]
Oh... well, this is not possible.
As a small town, we record all our townhall meetings, and there are ~50 recordings.
For existing rooms, since i have already learned the hard way that deleting a room also deletes all recordings attached to it.

**Comment by farhatahmad** [comment]
No recordings for that batch of rooms (since it fetches the recordings in batches)
