### ISSUE TITLE
Can't upload logo

### ISSUE THREAD

**Issue by lkrbbsb** [bigbluebutton/greenlight#5589]
When uploading our logo, it says that it can't be uploaded.

```
E, [2023-11-29T01:46:24.949115 #1] ERROR -- : [b820b419-bedf-4c44-9135-5f09dbbee639] Could not find or build blob: expected attachable, got #<ActionController::Parameters {} permitted: false>
E, [2023-11-29T01:46:24.949301 #1] ERROR -- : [b820b419-bedf-4c44-9135-5f09dbbee639] /usr/src/app/vendor/bundle/ruby/3.2.0/gems/activestorage-7.1.1/lib/active_storage/attached/changes/create_one.rb:112:in `find_or_build_blob'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activestorage-7.1.1/lib/active_storage/attached/changes/create_one.rb:20:in `blob'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activestorage-7.1.1/lib/active_storage/attached/changes/create_one.rb:12:in `initialize'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activestorage-7.1.1/lib/active_storage/attached/model.rb:109:in `new'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activestorage-7.1.1/lib/active_storage/attached/model.rb:109:in `image='
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activestorage-7.1.1/lib/active_storage/attached/one.rb:59:in `public_send'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activestorage-7.1.1/lib/active_storage/attached/one.rb:59:in `attach'
/usr/src/app/app/controllers/api/v1/admin/site_settings_controller.rb:49:in `update'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/abstract_controller/base.rb:224:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_controller/metal/rendering.rb:165:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/abstract_controller/callbacks.rb:259:in `block in process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actiontext-7.1.1/lib/action_text/rendering.rb:23:in `with_renderer'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actiontext-7.1.1/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:141:in `run_callbacks'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/abstract_controller/callbacks.rb:258:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_controller/metal/rescue.rb:25:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206:in `instrument'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_controller/metal/instrumentation.rb:73:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/railties/controller_runtime.rb:32:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/abstract_controller/base.rb:160:in `process'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionview-7.1.1/lib/action_view/rendering.rb:40:in `process'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_controller/metal.rb:227:in `dispatch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_controller/metal.rb:309:in `dispatch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/journey/router.rb:51:in `block in serve'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/journey/router.rb:124:in `each'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/journey/router.rb:124:in `find_routes'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/routing/route_set.rb:882:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/omniauth-2.1.1/lib/omniauth/builder.rb:44:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/etag.rb:27:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/conditional_get.rb:40:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/http/permissions_policy.rb:36:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/http/content_security_policy.rb:33:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:266:in `context'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:260:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/cookies.rb:689:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/rails/rack/logger.rb:24:in `block in call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/tagged_logging.rb:135:in `block in tagged'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/tagged_logging.rb:39:in `tagged'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/tagged_logging.rb:135:in `tagged'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/broadcast_logger.rb:232:in `method_missing'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/rails/rack/logger.rb:24:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/request_id.rb:28:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/method_override.rb:24:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/runtime.rb:22:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.1/lib/action_dispatch/middleware/static.rb:25:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/sendfile.rb:110:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/rails/engine.rb:529:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/urlmap.rb:74:in `block in call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/urlmap.rb:58:in `each'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/urlmap.rb:58:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.7/lib/puma/configuration.rb:252:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.7/lib/puma/request.rb:77:in `block in handle_request'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.7/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.7/lib/puma/request.rb:76:in `handle_request'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.7/lib/puma/server.rb:443:in `process_client'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.7/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by farhatahmad** [comment]
Thanks for the report - will be fixed in a hotfix shortly
