### ISSUE TITLE
Don't know how to build task 'migrations:roles'

### ISSUE THREAD

**Issue by aminir1400** [bigbluebutton/greenlight#5665]
Hi,
I installed the latest versions of BigBlueButton and Greenlight on a new server and want to migrate users, rooms, and other data from my old server to the new one. My old server has a customized version of Greenlight. I followed the instructions from https://docs.bigbluebutton.org/greenlight/v3/migration/, but I'm unable to complete the migration and am encountering the following error: 
Don't know how to build task 'migrations:roles'

My old server has Greenlight version 2.

**Comment by aminir1400** [comment]
I have downloaded migrations.rake from bellow address:
wget -P lib/tasks/migrations https://raw.githubusercontent.com/bigbluebutton/greenlight/v2/lib/tasks/migrations/migrations.rake

when I run 
sudo docker exec -it greenlight-v2 bundle exec rake migrations:roles 

bellow error is occurred. 
** Invoke migrations:roles (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
KeyError: key not found: "SMTP_SENDER_EMAIL" (KeyError)
Did you mean?  "SMTP_SENDER"

**Comment by aminir1400** [comment]
after put bellow section after  BIGBLUEBUTTON_ENDPOINT= BIGBLUEBUTTON_SECRET= section 
i get following error,
Please guide me. 
# The endpoint and "SECRET_KEY_BASE" for your Greenlight v3 instance.
# Set these if you are trying to migrate your resources to v3.
# Example:
#V3_ENDPOINT=https://v3.greenlight.test/
#V3_SECRET_KEY_BASE=
V3_ENDPOINT=
V3_SECRET_KEY_BASE=


error :

root@webinar:~/greenlight# sudo docker exec -it greenlight-v2 bundle exec rake migrations:roles
rake aborted!
NoMethodError: undefined method `red' for main:Object
/usr/src/app/lib/tasks/migrations/migrations.rake:29:in `block (3 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:70:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:70:in `block in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:222:in `loop'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/relation/batches.rb:69:in `find_each'
/usr/src/app/lib/tasks/migrations/migrations.rake:19:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => migrations:roles
