### ISSUE TITLE
Room migration fails

### ISSUE THREAD

**Issue by herzkerl** [bigbluebutton/greenlight#5767]
While migrating the rooms from v2 to v3, I'm getting the following error:

```
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/src/app/storage/Tw/eB/TweBjYAZTYDGkDYdE5ctyxrF
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activestorage-5.2.8.1/lib/active_storage/service/disk_service.rb:36:in `binread'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activestorage-5.2.8.1/lib/active_storage/service/disk_service.rb:36:in `block in download'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `instrument'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activestorage-5.2.8.1/lib/active_storage/service.rb:124:in `instrument'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activestorage-5.2.8.1/lib/active_storage/service/disk_service.rb:35:in `download'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activestorage-5.2.8.1/app/models/active_storage/blob.rb:165:in `download'
/usr/src/app/lib/tasks/migrations/migrations.rake:163:in `block (3 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `block in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:222:in `loop'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:69:in `find_each'
/usr/src/app/lib/tasks/migrations/migrations.rake:133:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => migrations:rooms
(See full trace by running task with --trace)
```

**Comment by TischKlaus** [comment]
After a bit of checking the issue appears to be that the presentation file is missing in the FS (/storage). Which makes sense in my case, because our test environment has only test data for the database.
This issue was introduced in 04c7288. In the added code there is a check if the room has a presentation attached to it, but not if the presentation actually exists as file. The file on the drive is only called when r.presentation.blob.download is engaged, meaning a missing file causes "No such file or directory".

As for a potential fix, Ruby is not my strong side.

**Comment by TischKlaus** [comment]
@danimo @farhatahmad 
Would it be possible to add a check to skip presentation mission on file system? As of now 1 missing presentation file stops the migration process.

**Comment by danimo** [comment]
Can you try to modify the code like so?

```ruby
if r.presentation.attached?
       begin
           params[:room][:presentation] = { blob: Base64.encode64(r.presentation.blob.download),
                                         filename: r.presentation.blob.filename.to_s }
       rescue Errno::ENOENT
           p "Failed to locate '#{r.presentation.blob.filename.to_s}' in active storage, skipping."
       end
```

**Comment by TischKlaus** [comment]
Sorry for the late response. Your code does work, the migrations run successful!
Thank you very much!

**Comment by farhatahmad** [comment]
@danimo Would you be able to send a PR for this please?

**Comment by danimo** [comment]
Done. Please merge.

**Comment by farhatahmad** [comment]
New version release 2.14.10 that should solve this
