### ISSUE TITLE
[v2 -> v3] Room migration: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by Commifreak** [bigbluebutton/greenlight#5819]
Hi.

I just tried to migrate v2 to v3 with latest greenlight v2 and v3.

All roles and users migrated successfully. However, I fail to migrate one room. Many otheres were migrated.

I get:

```
Unable to migrate Room:
UID: ric-ynm-smi-jlj
Name: **REMOVED** (but nothing special)
Provider: ldap
rake aborted!
JSON::ParserError: 859: unexpected token at '<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
/usr/src/app/lib/tasks/migrations/migrations.rake:183:in `block (3 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `block in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:222:in `loop'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:69:in `find_each'
/usr/src/app/lib/tasks/migrations/migrations.rake:133:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => migrations:rooms
(See full trace by running task with --trace)
```

Any ideas?

**Comment by Commifreak** [comment]
Increasing `client_max_body_size` from 31m to 51m does not helped.

**Comment by farhatahmad** [comment]
@danimo Seems like this issue is popping up more and more. Thoughts on a solution?

**Comment by danimo** [comment]
`client_max_body_size` should be the correct parameter. Are you sure you are putting in the right place in the nginx config file? Do not put it inside any `location` directive, but straight into the `server` one. And note that it needs to be set on the server behind the greenlight 3 nginx reverse proxy!
